package fixturemigrate

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Stamp is the layout of the timestamp in a migration file name.
const Stamp = "20060102150405"

// NextStamp is the timestamp for a new migration: now, or one second past the
// newest migration already there, whichever is later.
//
// bun runs pending migrations in name order, and a fixture migration is
// generated against the state every migration before it leaves: the previous
// fixture migration, and the schema migration that added the column it
// writes. A clock that is behind, or a migration somebody dated ahead, would
// otherwise put the new one first. It also never hands out a name already
// taken, which bun would record as one migration and run only once.
func NextStamp(now time.Time, existing []string) string {
	stamp := now.UTC().Format(Stamp)
	for _, name := range existing {
		if len(name) != len(Stamp) || name < stamp {
			continue
		}
		if t, err := time.Parse(Stamp, name); err == nil {
			stamp = t.Add(time.Second).Format(Stamp)
			continue
		}
		n, _ := strconv.ParseInt(name, 10, 64)
		stamp = fmt.Sprintf("%014d", n+1)
	}
	return stamp
}

// FileName is the name of the generated file: the timestamp, "fixture" and
// the slug of name, so it sorts into the migration chain where it belongs.
func FileName(stamp, name string) string { return stamp + "_fixture_" + Slug(name) + ".go" }

// VarName is the Go identifier of the change set in the generated file.
func VarName(stamp, name string) string {
	var camel strings.Builder
	for _, part := range strings.Split(Slug(name), "_") {
		if part == "" {
			continue
		}
		camel.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return "fixtureChanges" + stamp + camel.String()
}

// Slug lower-cases a name and replaces everything outside [0-9a-z_] with "_".
func Slug(name string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(strings.TrimSpace(name)) {
		if (r >= '0' && r <= '9') || (r >= 'a' && r <= 'z') || r == '_' {
			b.WriteRune(r)
			continue
		}
		b.WriteRune('_')
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		out = "changes"
	}
	return out
}

// Render writes the Go source of the migration. base is the revision the diff
// was taken against and appears in the file comment. Refused differences are
// listed as comments at the end, so the file says what it is missing.
//
// The result is gofmt-clean and meant to be read: a generator that writes
// hundreds of lines of SQL nobody reviews is worse than no generator.
func Render(cfg *Config, name, stamp string, res *Result) ([]byte, error) {
	if len(res.Changes) == 0 {
		return nil, fmt.Errorf("nothing to write")
	}
	set := fixturechange.Set{
		Name:            strings.TrimSuffix(FileName(stamp, name), ".go"),
		SeedGuardTable:  cfg.SeedGuardTable,
		MigrationsTable: cfg.MigrationsTable,
		Tables:          res.Tables,
		Changes:         res.Changes,
		Policy: fixturechange.Policy{
			MissingRow: fixturechange.Mode(cfg.Policy.MissingRow),
			ChangedRow: fixturechange.Mode(cfg.Policy.ChangedRow),
			IDDrift:    fixturechange.Mode(cfg.Policy.IDDrift),
		},
	}
	if err := fixtureapply.Validate(set); err != nil {
		return nil, fmt.Errorf("the change set this would write is not valid: %w", err)
	}
	ident := VarName(stamp, name)
	ins, upd, del := res.Totals()

	var b strings.Builder
	fmt.Fprintf(&b, "package %s\n\n", cfg.Package)
	b.WriteString("import (\n\t\"context\"\n\n")
	b.WriteString("\t\"github.com/RELAXccc/bun-fixture-migrate/fixtureapply\"\n")
	b.WriteString("\t\"github.com/RELAXccc/bun-fixture-migrate/fixturechange\"\n\n")
	b.WriteString("\t\"github.com/uptrace/bun\"\n)\n\n")

	fmt.Fprintf(&b, "// Generated by bun-fixture-migrate: %s against %s.\n", res.Head, res.Base)
	fmt.Fprintf(&b, "// %s, %s, %s.\n", plural(ins, "insert"), plural(upd, "update"), plural(del, "delete"))
	b.WriteString("//\n")
	for _, line := range res.Summary() {
		fmt.Fprintf(&b, "// %s\n", line)
	}
	b.WriteString("//\n")
	b.WriteString("// Read it before you run it. Each change is guarded: a row is found by its\n")
	b.WriteString("// natural key, an update or a delete only touches a row that still holds the\n")
	b.WriteString("// old values, and an insert only runs when no row with that key exists.\n")
	b.WriteString("// A guard that matches nothing is diagnosed rather than ignored, and unless\n")
	b.WriteString("// Policy says otherwise it fails the migration. A failed migration is not\n")
	b.WriteString("// left recorded as applied: if bun recorded it before running it, which it\n")
	b.WriteString("// does unless the migrator is built WithMarkAppliedOnSuccess(true), Apply\n")
	b.WriteString("// removes that record from MigrationsTable so the migration runs again.\n")

	b.WriteString("func init() {\n")
	fmt.Fprintf(&b, "\t%s.MustRegister(func(ctx context.Context, db *bun.DB) error {\n", cfg.Migrator)
	fmt.Fprintf(&b, "\t\treturn fixtureapply.Apply(ctx, db, %s)\n", ident)
	b.WriteString("\t}, func(ctx context.Context, db *bun.DB) error {\n")
	fmt.Fprintf(&b, "\t\treturn fixtureapply.Revert(ctx, db, %s)\n", ident)
	b.WriteString("\t})\n}\n\n")

	fmt.Fprintf(&b, "var %s = fixturechange.Set{\n", ident)
	fmt.Fprintf(&b, "\tName: %q,\n", set.Name)
	if set.SeedGuardTable != "" {
		fmt.Fprintf(&b, "\tSeedGuardTable: %q,\n", set.SeedGuardTable)
	}
	if set.MigrationsTable != "" {
		fmt.Fprintf(&b, "\tMigrationsTable: %q,\n", set.MigrationsTable)
	}
	b.WriteString("\tTables: fixturechange.Tables{\n")
	for _, model := range sortedKeys(res.Tables) {
		t := res.Tables[model]
		fmt.Fprintf(&b, "\t\t%q: {Name: %q, ID: %q", model, t.Name, t.ID)
		if t.Key != "" {
			fmt.Fprintf(&b, ", Key: %q", t.Key)
		}
		if t.Serial {
			b.WriteString(", Serial: true")
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t},\n")
	fmt.Fprintf(&b, "\tPolicy: fixturechange.Policy{MissingRow: %q, ChangedRow: %q, IDDrift: %q},\n",
		set.Policy.MissingRow, set.Policy.ChangedRow, set.Policy.IDDrift)
	b.WriteString("\tChanges: []fixturechange.Change{\n")
	for _, c := range res.Changes {
		fmt.Fprintf(&b, "\t\t{Model: %q, Kind: fixturechange.%s,\n", c.Model, kindIdent(c.Kind))
		if c.ID != "" {
			fmt.Fprintf(&b, "\t\t\tID: %q,\n", c.ID)
		}
		fmt.Fprintf(&b, "\t\t\tKey: %s,\n", renderValues(c.Key))
		if len(c.Old) > 0 {
			fmt.Fprintf(&b, "\t\t\tOld: %s,\n", renderValues(c.Old))
		}
		if len(c.New) > 0 {
			fmt.Fprintf(&b, "\t\t\tNew: %s,\n", renderValues(c.New))
		}
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t},\n}\n")

	if len(res.Refusals) > 0 {
		b.WriteString("\n// Left out, write these yourself:\n")
		for _, r := range res.Refusals {
			fmt.Fprintf(&b, "//\t%s\n", r.String())
		}
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("the generated file does not parse, which is a bug in this tool: %w", err)
	}
	return src, nil
}

func kindIdent(k fixturechange.Kind) string {
	switch k {
	case fixturechange.Update:
		return "Update"
	case fixturechange.Delete:
		return "Delete"
	default:
		return "Insert"
	}
}

// renderValues keeps short maps on one line and breaks longer ones up, because
// a whole inserted row on a single line is not something anyone reviews.
func renderValues(v fixturechange.Values) string {
	parts := make([]string, 0, len(v))
	for _, col := range sortedColumns(v) {
		val := v[col]
		switch {
		case val.IsNull:
			parts = append(parts, fmt.Sprintf("%q: fixturechange.Null()", col))
		case val.Ref != nil:
			parts = append(parts, fmt.Sprintf("%q: fixturechange.RefTo(%q, %q)", col, val.Ref.Model, val.Ref.Key))
		default:
			parts = append(parts, fmt.Sprintf("%q: fixturechange.Lit(%q)", col, val.Lit))
		}
	}
	if len(parts) <= 3 {
		return "fixturechange.Values{" + strings.Join(parts, ", ") + "}"
	}
	return "fixturechange.Values{\n\t\t\t\t" + strings.Join(parts, ",\n\t\t\t\t") + ",\n\t\t\t}"
}

func sortedKeys(t fixturechange.Tables) []string {
	out := make([]string, 0, len(t))
	for k := range t {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
