package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/fixture.yml against the state after baseline.
// 2 inserts, 1 update, 0 deletes.
//
// Plan: 1 insert, 1 update
// Feature: 1 insert
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20260930165255PlanPrices),
		fixtureapply.Down(fixtureChanges20260930165255PlanPrices),
	)
}

var fixtureChanges20260930165255PlanPrices = fixturechange.Set{
	Name:            "20260930165255_fixture_plan_prices",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Currency": {Name: "currencies", ID: "id", Key: "code"},
		"Feature":  {Name: "features", ID: "id", Serial: true},
		"Plan":     {Name: "plans", ID: "id", Key: "name", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Plan", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"name": fixturechange.Lit("pro")},
			New: fixturechange.Values{
				"currency_id": fixturechange.RefTo("Currency", "USD"),
				"id":          fixturechange.Lit("3"),
				"name":        fixturechange.Lit("pro"),
				"note":        fixturechange.Null(),
				"price_cents": fixturechange.Lit("9000"),
				"seats":       fixturechange.Lit("100"),
				"settings":    fixturechange.Lit(`{"sso":true,"trial_days":30}`),
			},
		},
		{Model: "Feature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"code":    fixturechange.Lit("api"),
				"plan_id": fixturechange.RefTo("Plan", "pro"),
			},
			New: fixturechange.Values{
				"code":    fixturechange.Lit("api"),
				"plan_id": fixturechange.RefTo("Plan", "pro"),
				"quota":   fixturechange.Lit("50000"),
			},
		},
		{Model: "Plan", Kind: fixturechange.Update,
			Key: fixturechange.Values{"name": fixturechange.Lit("team")},
			Old: fixturechange.Values{
				"note":        fixturechange.Null(),
				"price_cents": fixturechange.Lit("2000"),
				"settings":    fixturechange.Lit(`{"sso":false,"trial_days":14}`),
			},
			New: fixturechange.Values{
				"note":        fixturechange.Lit("most popular"),
				"price_cents": fixturechange.Lit("2500"),
				"settings":    fixturechange.Lit(`{"sso":true,"trial_days":14}`),
			},
		},
	},
}
