package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/fixture.yml against the state after 20260504100000_fixture_billing_admin_and_folded_edits.
// 13 inserts, 0 updates, 0 deletes.
//
// Plan: 1 insert
// PlanPrice: 3 inserts
// PlanFeature: 6 inserts
// Translation: 3 inserts
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20260601100000EnterprisePlan),
		fixtureapply.Down(fixtureChanges20260601100000EnterprisePlan),
	)
}

var fixtureChanges20260601100000EnterprisePlan = fixturechange.Set{
	Name:            "20260601100000_fixture_enterprise_plan",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Currency":    {Name: "currencies", ID: "id", Key: "code", Serial: true},
		"Feature":     {Name: "features", ID: "id", Key: "code", Serial: true},
		"Plan":        {Name: "plans", ID: "id", Key: "code"},
		"PlanFeature": {Name: "plan_features", ID: "id"},
		"PlanPrice":   {Name: "plan_prices", ID: "id", Serial: true},
		"Translation": {Name: "translations", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Plan", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("enterprise")},
			New: fixturechange.Values{
				"active":     fixturechange.Lit("true"),
				"code":       fixturechange.Lit("enterprise"),
				"name":       fixturechange.Lit("Enterprise"),
				"settings":   fixturechange.Lit(`{"audit":{"retention_days":3650},"max_projects":null,"sla":"99.95","sso":true,"support":"dedicated"}`),
				"sort_order": fixturechange.Lit("5"),
				"tags":       fixturechange.Lit(`["annual","contract"]`),
				"tier":       fixturechange.Lit("enterprise"),
				"trial_days": fixturechange.Lit("30"),
			},
		},
		{Model: "PlanPrice", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"currency_id": fixturechange.RefTo("Currency", "EUR"),
				"plan_id":     fixturechange.RefTo("Plan", "enterprise"),
				"valid_from":  fixturechange.Lit("2026-07-01"),
			},
			New: fixturechange.Values{
				"amount":      fixturechange.Lit("499"),
				"currency_id": fixturechange.RefTo("Currency", "EUR"),
				"plan_id":     fixturechange.RefTo("Plan", "enterprise"),
				"valid_from":  fixturechange.Lit("2026-07-01"),
			},
		},
		{Model: "PlanPrice", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"currency_id": fixturechange.RefTo("Currency", "USD"),
				"plan_id":     fixturechange.RefTo("Plan", "enterprise"),
				"valid_from":  fixturechange.Lit("2026-07-01"),
			},
			New: fixturechange.Values{
				"amount":      fixturechange.Lit("549"),
				"currency_id": fixturechange.RefTo("Currency", "USD"),
				"plan_id":     fixturechange.RefTo("Plan", "enterprise"),
				"valid_from":  fixturechange.Lit("2026-07-01"),
			},
		},
		{Model: "PlanPrice", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"currency_id": fixturechange.RefTo("Currency", "CHF"),
				"plan_id":     fixturechange.RefTo("Plan", "enterprise"),
				"valid_from":  fixturechange.Lit("2026-07-01"),
			},
			New: fixturechange.Values{
				"amount":      fixturechange.Lit("479.95"),
				"currency_id": fixturechange.RefTo("Currency", "CHF"),
				"plan_id":     fixturechange.RefTo("Plan", "enterprise"),
				"valid_from":  fixturechange.Lit("2026-07-01"),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "projects"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "projects"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "storage"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "storage"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "api"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "api"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "sso"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "sso"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "priority_support"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "priority_support"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "audit_log"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "audit_log"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"key":    fixturechange.Lit("plan.enterprise.name"),
				"locale": fixturechange.Lit("en"),
			},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("plan.enterprise.name"),
				"locale":  fixturechange.Lit("en"),
				"value":   fixturechange.Lit("Enterprise"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"key":    fixturechange.Lit("plan.enterprise.name"),
				"locale": fixturechange.Lit("de"),
			},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("plan.enterprise.name"),
				"locale":  fixturechange.Lit("de"),
				"value":   fixturechange.Lit("Enterprise"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"key":    fixturechange.Lit("plan.enterprise.name"),
				"locale": fixturechange.Lit("fr"),
			},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("plan.enterprise.name"),
				"locale":  fixturechange.Lit("fr"),
				"value":   fixturechange.Lit("Entreprise+"),
			},
		},
	},
}
