package migrations

import (
	"context"

	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"

	"github.com/uptrace/bun"
)

// Generated by bun-fixture-migrate: fixtures/fixture.yml against the state after 20260209100000_fixture_plan_prices_and_scale_plan.
// 11 inserts, 3 updates, 0 deletes.
//
// Currency: 1 insert
// Country: 1 insert
// Plan: 3 updates
// Translation: 9 inserts
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Apply
// removes that record from MigrationsTable so the migration runs again.
func init() {
	Migrations.MustRegister(func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Apply(ctx, db, fixtureChanges20260309100000TrialDaysAndFrench)
	}, func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Revert(ctx, db, fixtureChanges20260309100000TrialDaysAndFrench)
	})
}

var fixtureChanges20260309100000TrialDaysAndFrench = fixturechange.Set{
	Name:            "20260309100000_fixture_trial_days_and_french",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Country":     {Name: "countries", ID: "id", Serial: true},
		"Currency":    {Name: "currencies", ID: "id", Key: "code", Serial: true},
		"Plan":        {Name: "plans", ID: "id"},
		"Translation": {Name: "translations", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Currency", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("CHF")},
			New: fixturechange.Values{
				"code":        fixturechange.Lit("CHF"),
				"id":          fixturechange.Lit("4"),
				"minor_units": fixturechange.Lit("2"),
				"name":        fixturechange.Lit("Swiss franc"),
				"symbol":      fixturechange.Lit("CHF"),
			},
		},
		{Model: "Country", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("CH")},
			New: fixturechange.Values{
				"code":        fixturechange.Lit("CH"),
				"currency_id": fixturechange.RefTo("Currency", "CHF"),
				"id":          fixturechange.Lit("5"),
				"name":        fixturechange.Lit("Schweiz"),
				"tax_rate":    fixturechange.Lit("0.081"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"key": fixturechange.Lit("plan.free.name"), "locale": fixturechange.Lit("fr")},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("plan.free.name"),
				"locale":  fixturechange.Lit("fr"),
				"value":   fixturechange.Lit("Gratuit"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"key": fixturechange.Lit("plan.team.name"), "locale": fixturechange.Lit("fr")},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("plan.team.name"),
				"locale":  fixturechange.Lit("fr"),
				"value":   fixturechange.Lit("Équipe"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"key":    fixturechange.Lit("plan.business.name"),
				"locale": fixturechange.Lit("fr"),
			},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("plan.business.name"),
				"locale":  fixturechange.Lit("fr"),
				"value":   fixturechange.Lit("Entreprise"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"key": fixturechange.Lit("plan.scale.name"), "locale": fixturechange.Lit("fr")},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("plan.scale.name"),
				"locale":  fixturechange.Lit("fr"),
				"value":   fixturechange.Lit("Scale"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"key": fixturechange.Lit("nav.billing"), "locale": fixturechange.Lit("fr")},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("nav.billing"),
				"locale":  fixturechange.Lit("fr"),
				"value":   fixturechange.Lit("Facturation"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"key": fixturechange.Lit("nav.settings"), "locale": fixturechange.Lit("fr")},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("nav.settings"),
				"locale":  fixturechange.Lit("fr"),
				"value":   fixturechange.Lit("Paramètres"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"key":    fixturechange.Lit("errors.quota_exceeded"),
				"locale": fixturechange.Lit("fr"),
			},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("errors.quota_exceeded"),
				"locale":  fixturechange.Lit("fr"),
				"value":   fixturechange.Lit("Vous avez utilisé les {{quota}} {{feature}} de votre forfait."),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"key":    fixturechange.Lit("email.welcome.subject"),
				"locale": fixturechange.Lit("fr"),
			},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("email.welcome.subject"),
				"locale":  fixturechange.Lit("fr"),
				"value":   fixturechange.Lit("Bienvenue chez Acme\u202f!"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"key":    fixturechange.Lit("email.welcome.body"),
				"locale": fixturechange.Lit("fr"),
			},
			New: fixturechange.Values{
				"context": fixturechange.Lit("Plain-text e-mail; keep the placeholders."),
				"key":     fixturechange.Lit("email.welcome.body"),
				"locale":  fixturechange.Lit("fr"),
				"value":   fixturechange.Lit("Bonjour {name},\n\nbienvenue chez Acme. Votre espace « {workspace} » est prêt.\nUne question ? Répondez à cet e-mail : un humain le lit.\n"),
			},
		},
		{Model: "Plan", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("free")},
			Old: fixturechange.Values{"trial_days": fixturechange.Lit("14")},
			New: fixturechange.Values{"trial_days": fixturechange.Lit("0")},
		},
		{Model: "Plan", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("business")},
			Old: fixturechange.Values{"trial_days": fixturechange.Lit("14")},
			New: fixturechange.Values{"trial_days": fixturechange.Lit("30")},
		},
		{Model: "Plan", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("scale")},
			Old: fixturechange.Values{"trial_days": fixturechange.Lit("14")},
			New: fixturechange.Values{"trial_days": fixturechange.Lit("30")},
		},
	},
}
