package migrations

import (
	"context"

	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"

	"github.com/uptrace/bun"
)

// Generated by bun-fixture-migrate: fixtures/fixture.yml against the state after 20260406100000_fixture_quotas_and_labels.
// 3 inserts, 4 updates, 0 deletes.
//
// Role: 1 insert
// Permission: 2 updates
// RolePermission: 2 inserts
// Translation: 2 updates
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Apply
// removes that record from MigrationsTable so the migration runs again.
func init() {
	Migrations.MustRegister(func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Apply(ctx, db, fixtureChanges20260504100000BillingAdminAndFoldedEdits)
	}, func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Revert(ctx, db, fixtureChanges20260504100000BillingAdminAndFoldedEdits)
	})
}

var fixtureChanges20260504100000BillingAdminAndFoldedEdits = fixturechange.Set{
	Name:            "20260504100000_fixture_billing_admin_and_folded_edits",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Permission":     {Name: "permissions", ID: "id", Key: "code", Serial: true},
		"Role":           {Name: "roles", ID: "id", Key: "code", Serial: true},
		"RolePermission": {Name: "role_permissions", ID: "id"},
		"Translation":    {Name: "translations", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{MissingRow: "error", ChangedRow: "warn", IDDrift: "error"},
	Changes: []fixturechange.Change{
		{Model: "Permission", Kind: fixturechange.Update,
			ID:  "2",
			Key: fixturechange.Values{"code": fixturechange.Lit("billing.write")},
			Old: fixturechange.Values{"code": fixturechange.Lit("billing.write")},
			New: fixturechange.Values{"code": fixturechange.Lit("billing.manage")},
		},
		{Model: "Role", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("billing_admin")},
			New: fixturechange.Values{
				"code":      fixturechange.Lit("billing_admin"),
				"id":        fixturechange.Lit("100"),
				"name":      fixturechange.Lit("Billing administrator"),
				"tenant_id": fixturechange.Null(),
			},
		},
		{Model: "RolePermission", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"permission_id": fixturechange.RefTo("Permission", "billing.read"),
				"role_id":       fixturechange.RefTo("Role", "billing_admin"),
			},
			New: fixturechange.Values{
				"permission_id": fixturechange.RefTo("Permission", "billing.read"),
				"role_id":       fixturechange.RefTo("Role", "billing_admin"),
			},
		},
		{Model: "RolePermission", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"permission_id": fixturechange.RefTo("Permission", "billing.manage"),
				"role_id":       fixturechange.RefTo("Role", "billing_admin"),
			},
			New: fixturechange.Values{
				"permission_id": fixturechange.RefTo("Permission", "billing.manage"),
				"role_id":       fixturechange.RefTo("Role", "billing_admin"),
			},
		},
		{Model: "Permission", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("billing.manage")},
			Old: fixturechange.Values{"description": fixturechange.Lit("Change the plan and the payment method")},
			New: fixturechange.Values{
				"description": fixturechange.Lit("Change the plan, the payment method and the billing address"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Update,
			Key: fixturechange.Values{"key": fixturechange.Lit("nav.billing"), "locale": fixturechange.Lit("en")},
			Old: fixturechange.Values{"value": fixturechange.Lit("Billing and invoices")},
			New: fixturechange.Values{"value": fixturechange.Lit("Billing & invoices")},
		},
		{Model: "Translation", Kind: fixturechange.Update,
			Key: fixturechange.Values{
				"key":    fixturechange.Lit("email.welcome.subject"),
				"locale": fixturechange.Lit("de"),
			},
			Old: fixturechange.Values{"value": fixturechange.Lit("Willkommen bei Acme!")},
			New: fixturechange.Values{"value": fixturechange.Lit("Willkommen an Bord, {name}!")},
		},
	},
}
