package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/access.yml, fixtures/i18n.yml, fixtures/help.yml against the state after 20261116100000_fixture_help_centre.
// 3 inserts, 0 updates, 0 deletes.
//
// Role: 1 insert
// RolePermission: 2 inserts
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20261207100000SupportRole),
		fixtureapply.Down(fixtureChanges20261207100000SupportRole),
	)
}

var fixtureChanges20261207100000SupportRole = fixturechange.Set{
	Name:            "20261207100000_fixture_support_role",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Permission":     {Name: "permissions", ID: "id", Key: "code", Serial: true},
		"Role":           {Name: "roles", ID: "id", Key: "code", Serial: true, Where: "tenant_id IS NULL"},
		"RolePermission": {Name: "role_permissions", ID: "id", Where: "role_id IN (SELECT id FROM roles WHERE tenant_id IS NULL)"},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Role", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("support")},
			New: fixturechange.Values{
				"code":      fixturechange.Lit("support"),
				"name":      fixturechange.Lit("Support agent"),
				"tenant_id": fixturechange.Null(),
			},
		},
		{Model: "RolePermission", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"permission_id": fixturechange.RefTo("Permission", "billing.read"),
				"role_id":       fixturechange.RefTo("Role", "support"),
			},
			New: fixturechange.Values{
				"permission_id": fixturechange.RefTo("Permission", "billing.read"),
				"role_id":       fixturechange.RefTo("Role", "support"),
			},
		},
		{Model: "RolePermission", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"permission_id": fixturechange.RefTo("Permission", "projects.read"),
				"role_id":       fixturechange.RefTo("Role", "support"),
			},
			New: fixturechange.Values{
				"permission_id": fixturechange.RefTo("Permission", "projects.read"),
				"role_id":       fixturechange.RefTo("Role", "support"),
			},
		},
	},
}
