package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/access.yml, fixtures/i18n.yml against the state after 20260824100000_fixture_platform_categories.
// 4 inserts, 0 updates, 0 deletes.
//
// Feature: 1 insert
// PlanFeature: 1 insert
// Translation: 2 inserts
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20260914100000Scim),
		fixtureapply.Down(fixtureChanges20260914100000Scim),
	)
}

var fixtureChanges20260914100000Scim = fixturechange.Set{
	Name:            "20260914100000_fixture_scim",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Feature":     {Name: "features", ID: "id", Key: "code", Serial: true},
		"Plan":        {Name: "plans", ID: "id", Key: "code"},
		"PlanFeature": {Name: "plan_features", ID: "id"},
		"Translation": {Name: "translations", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Feature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("scim")},
			New: fixturechange.Values{
				"code": fixturechange.Lit("scim"),
				"id":   fixturechange.Lit("7"),
				"name": fixturechange.Lit("SCIM provisioning"),
				"unit": fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "scim"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "scim"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"key":    fixturechange.Lit("feature.scim.name"),
				"locale": fixturechange.Lit("en"),
			},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("feature.scim.name"),
				"locale":  fixturechange.Lit("en"),
				"value":   fixturechange.Lit("SCIM provisioning"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"key":    fixturechange.Lit("feature.scim.name"),
				"locale": fixturechange.Lit("de"),
			},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("feature.scim.name"),
				"locale":  fixturechange.Lit("de"),
				"value":   fixturechange.Lit("SCIM-Provisionierung"),
			},
		},
	},
}
