package migrations

import (
	"context"

	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"

	"github.com/uptrace/bun"
)

// Generated by bun-fixture-migrate: fixtures/fixture.yml against the state after 20260309100000_fixture_trial_days_and_french.
// 0 inserts, 5 updates, 0 deletes.
//
// Feature: 1 update
// PlanFeature: 2 updates
// Translation: 2 updates
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Apply
// removes that record from MigrationsTable so the migration runs again.
func init() {
	Migrations.MustRegister(func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Apply(ctx, db, fixtureChanges20260406100000QuotasAndLabels)
	}, func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Revert(ctx, db, fixtureChanges20260406100000QuotasAndLabels)
	})
}

var fixtureChanges20260406100000QuotasAndLabels = fixturechange.Set{
	Name:            "20260406100000_fixture_quotas_and_labels",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Feature":     {Name: "features", ID: "id", Key: "code", Serial: true},
		"Plan":        {Name: "plans", ID: "id", Key: "code"},
		"PlanFeature": {Name: "plan_features", ID: "id"},
		"Translation": {Name: "translations", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{MissingRow: "error", ChangedRow: "warn", IDDrift: "error"},
	Changes: []fixturechange.Change{
		{Model: "Feature", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("api")},
			Old: fixturechange.Values{"name": fixturechange.Lit("API requests")},
			New: fixturechange.Values{"name": fixturechange.Lit("API calls")},
		},
		{Model: "PlanFeature", Kind: fixturechange.Update,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "projects"),
				"plan_id":    fixturechange.RefTo("Plan", "free"),
			},
			Old: fixturechange.Values{"quota": fixturechange.Lit("3")},
			New: fixturechange.Values{"quota": fixturechange.Lit("5")},
		},
		{Model: "PlanFeature", Kind: fixturechange.Update,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "storage"),
				"plan_id":    fixturechange.RefTo("Plan", "team"),
			},
			Old: fixturechange.Values{"quota": fixturechange.Lit("100")},
			New: fixturechange.Values{"quota": fixturechange.Lit("200")},
		},
		{Model: "Translation", Kind: fixturechange.Update,
			Key: fixturechange.Values{"key": fixturechange.Lit("nav.billing"), "locale": fixturechange.Lit("en")},
			Old: fixturechange.Values{"value": fixturechange.Lit("Billing")},
			New: fixturechange.Values{"value": fixturechange.Lit("Billing and invoices")},
		},
		{Model: "Translation", Kind: fixturechange.Update,
			Key: fixturechange.Values{
				"key":    fixturechange.Lit("email.welcome.subject"),
				"locale": fixturechange.Lit("de"),
			},
			Old: fixturechange.Values{"context": fixturechange.Null()},
			New: fixturechange.Values{
				"context": fixturechange.Lit("Subject line of the welcome e-mail, at most 60 characters."),
			},
		},
	},
}
