package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/access.yml, fixtures/i18n.yml against the state after baseline.
// 0 inserts, 2 updates, 0 deletes.
//
// Plan: 2 updates
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20261019100000PlanOrder),
		fixtureapply.Down(fixtureChanges20261019100000PlanOrder),
	)
}

var fixtureChanges20261019100000PlanOrder = fixturechange.Set{
	Name:            "20261019100000_fixture_plan_order",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Plan": {Name: "plans", ID: "id"},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Plan", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("scale")},
			Old: fixturechange.Values{"position": fixturechange.Lit("4")},
			New: fixturechange.Values{"position": fixturechange.Lit("9")},
		},
		{Model: "Plan", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("enterprise")},
			Old: fixturechange.Values{"position": fixturechange.Lit("5")},
			New: fixturechange.Values{"position": fixturechange.Lit("4")},
		},
	},
}
