package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/access.yml, fixtures/i18n.yml against the state after 20260601100000_fixture_enterprise_plan.
// 0 inserts, 1 update, 4 deletes.
//
// Plan: 1 update
// Feature: 1 delete
// PlanFeature: 3 deletes
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20260727100000RetireScaleAndPrioritySupport),
		fixtureapply.Down(fixtureChanges20260727100000RetireScaleAndPrioritySupport),
	)
}

var fixtureChanges20260727100000RetireScaleAndPrioritySupport = fixturechange.Set{
	Name:            "20260727100000_fixture_retire_scale_and_priority_support",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Feature":     {Name: "features", ID: "id", Key: "code", Serial: true},
		"Plan":        {Name: "plans", ID: "id", Key: "code"},
		"PlanFeature": {Name: "plan_features", ID: "id"},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "PlanFeature", Kind: fixturechange.Delete,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "priority_support"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
			},
			Old: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "priority_support"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Delete,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "priority_support"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
			},
			Old: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "priority_support"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Delete,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "priority_support"),
				"plan_id":    fixturechange.RefTo("Plan", "business"),
			},
			Old: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "priority_support"),
				"plan_id":    fixturechange.RefTo("Plan", "business"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "Feature", Kind: fixturechange.Delete,
			Key: fixturechange.Values{"code": fixturechange.Lit("priority_support")},
			Old: fixturechange.Values{
				"code": fixturechange.Lit("priority_support"),
				"id":   fixturechange.Lit("5"),
				"name": fixturechange.Lit("Priority support"),
				"unit": fixturechange.Null(),
			},
		},
		{Model: "Plan", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("scale")},
			Old: fixturechange.Values{"active": fixturechange.Lit("true")},
			New: fixturechange.Values{"active": fixturechange.Lit("false")},
		},
	},
}
