package migrations

import (
	"context"

	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"

	"github.com/uptrace/bun"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/access.yml, fixtures/i18n.yml against the database.
// 0 inserts, 1 update, 0 deletes.
//
// Category: 1 update
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Apply
// removes that record from MigrationsTable so the migration runs again.
func init() {
	Migrations.MustRegister(func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Apply(ctx, db, fixtureChanges20261005100000DashboardsNameAsInTheFile)
	}, func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Revert(ctx, db, fixtureChanges20261005100000DashboardsNameAsInTheFile)
	})
}

var fixtureChanges20261005100000DashboardsNameAsInTheFile = fixturechange.Set{
	Name:            "20261005100000_fixture_dashboards_name_as_in_the_file",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Category": {Name: "categories", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("dashboards")},
			Old: fixturechange.Values{"name": fixturechange.Lit("Dashboards & reports")},
			New: fixturechange.Values{"name": fixturechange.Lit("Dashboards")},
		},
	},
}
