package migrations

import (
	"context"

	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"

	"github.com/uptrace/bun"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/access.yml, fixtures/i18n.yml against the state after 20260824100000_fixture_platform_categories.
// 3 inserts, 1 update, 0 deletes.
//
// Feature: 1 insert
// PlanFeature: 2 inserts
// Translation: 1 update
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Apply
// removes that record from MigrationsTable so the migration runs again.
func init() {
	Migrations.MustRegister(func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Apply(ctx, db, fixtureChanges20260915100000DataResidency)
	}, func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Revert(ctx, db, fixtureChanges20260915100000DataResidency)
	})
}

var fixtureChanges20260915100000DataResidency = fixturechange.Set{
	Name:            "20260915100000_fixture_data_residency",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Feature":     {Name: "features", ID: "id", Key: "code", Serial: true},
		"Plan":        {Name: "plans", ID: "id", Key: "code"},
		"PlanFeature": {Name: "plan_features", ID: "id"},
		"Translation": {Name: "translations", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{MissingRow: "error", ChangedRow: "warn", IDDrift: "error"},
	Changes: []fixturechange.Change{
		{Model: "Feature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("data_residency")},
			New: fixturechange.Values{
				"code": fixturechange.Lit("data_residency"),
				"id":   fixturechange.Lit("8"),
				"name": fixturechange.Lit("Data residency"),
				"unit": fixturechange.Lit("region"),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "data_residency"),
				"plan_id":    fixturechange.RefTo("Plan", "business"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "data_residency"),
				"plan_id":    fixturechange.RefTo("Plan", "business"),
				"quota":      fixturechange.Lit("1"),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "data_residency"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "data_residency"),
				"plan_id":    fixturechange.RefTo("Plan", "enterprise"),
				"quota":      fixturechange.Lit("3"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Update,
			Key: fixturechange.Values{"key": fixturechange.Lit("nav.settings"), "locale": fixturechange.Lit("en")},
			Old: fixturechange.Values{"value": fixturechange.Lit("Settings")},
			New: fixturechange.Values{"value": fixturechange.Lit("Settings & data residency")},
		},
	},
}
