package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/access.yml, fixtures/i18n.yml against the state after 20260727100000_fixture_retire_scale_and_priority_support.
// 2 inserts, 3 updates, 0 deletes.
//
// Category: 2 inserts, 3 updates
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20260824100000PlatformCategories),
		fixtureapply.Down(fixtureChanges20260824100000PlatformCategories),
	)
}

var fixtureChanges20260824100000PlatformCategories = fixturechange.Set{
	Name:            "20260824100000_fixture_platform_categories",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Category": {Name: "categories", ID: "id", Key: "slug", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Category", Kind: fixturechange.Update,
			ID:  "1",
			Key: fixturechange.Values{"slug": fixturechange.Lit("integrations")},
			Old: fixturechange.Values{"slug": fixturechange.Lit("integrations")},
			New: fixturechange.Values{"slug": fixturechange.Lit("platform")},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("platform")},
			Old: fixturechange.Values{"name": fixturechange.Lit("Integrations")},
			New: fixturechange.Values{"name": fixturechange.Lit("Platform")},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("analytics")},
			Old: fixturechange.Values{"parent_id": fixturechange.Null(), "position": fixturechange.Lit("2")},
			New: fixturechange.Values{
				"parent_id": fixturechange.RefTo("Category", "platform"),
				"position":  fixturechange.Lit("3"),
			},
		},
		{Model: "Category", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"slug": fixturechange.Lit("developer-tools")},
			New: fixturechange.Values{
				"id":        fixturechange.Lit("10"),
				"name":      fixturechange.Lit("Developer tools"),
				"parent_id": fixturechange.Null(),
				"position":  fixturechange.Lit("2"),
				"slug":      fixturechange.Lit("developer-tools"),
			},
		},
		{Model: "Category", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"slug": fixturechange.Lit("sdks")},
			New: fixturechange.Values{
				"id":        fixturechange.Lit("11"),
				"name":      fixturechange.Lit("SDKs"),
				"parent_id": fixturechange.RefTo("Category", "developer-tools"),
				"position":  fixturechange.Lit("1"),
				"slug":      fixturechange.Lit("sdks"),
			},
		},
	},
}
