package migrations

import (
	"context"

	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"

	"github.com/uptrace/bun"
)

// Generated by bun-fixture-migrate: fixtures/fixture.yml against the state after baseline.
// 15 inserts, 0 updates, 0 deletes.
//
// Plan: 1 insert
// PlanPrice: 4 inserts
// Feature: 1 insert
// PlanFeature: 7 inserts
// Translation: 2 inserts
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Apply
// removes that record from MigrationsTable so the migration runs again.
func init() {
	Migrations.MustRegister(func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Apply(ctx, db, fixtureChanges20260209100000PlanPricesAndScalePlan)
	}, func(ctx context.Context, db *bun.DB) error {
		return fixtureapply.Revert(ctx, db, fixtureChanges20260209100000PlanPricesAndScalePlan)
	})
}

var fixtureChanges20260209100000PlanPricesAndScalePlan = fixturechange.Set{
	Name:            "20260209100000_fixture_plan_prices_and_scale_plan",
	SeedGuardTable:  "plans",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Currency":    {Name: "currencies", ID: "id", Key: "code", Serial: true},
		"Feature":     {Name: "features", ID: "id", Key: "code", Serial: true},
		"Plan":        {Name: "plans", ID: "id", Key: "code"},
		"PlanFeature": {Name: "plan_features", ID: "id"},
		"PlanPrice":   {Name: "plan_prices", ID: "id", Serial: true},
		"Translation": {Name: "translations", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{MissingRow: "error", ChangedRow: "warn", IDDrift: "error"},
	Changes: []fixturechange.Change{
		{Model: "Plan", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("scale")},
			New: fixturechange.Values{
				"active":     fixturechange.Lit("true"),
				"code":       fixturechange.Lit("scale"),
				"name":       fixturechange.Lit("Scale"),
				"settings":   fixturechange.Lit(`{"sso": true, "audit": {"retention_days": 365}, "support": "dedicated", "max_projects": 5000}`),
				"sort_order": fixturechange.Lit("4"),
				"tags":       fixturechange.Lit(`["annual", "enterprise-ready"]`),
				"tier":       fixturechange.Lit("business"),
			},
		},
		{Model: "PlanPrice", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"currency_id": fixturechange.RefTo("Currency", "EUR"),
				"plan_id":     fixturechange.RefTo("Plan", "team"),
				"valid_from":  fixturechange.Lit("2026-04-01"),
			},
			New: fixturechange.Values{
				"amount":      fixturechange.Lit("35"),
				"currency_id": fixturechange.RefTo("Currency", "EUR"),
				"plan_id":     fixturechange.RefTo("Plan", "team"),
				"valid_from":  fixturechange.Lit("2026-04-01"),
			},
		},
		{Model: "PlanPrice", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"currency_id": fixturechange.RefTo("Currency", "USD"),
				"plan_id":     fixturechange.RefTo("Plan", "team"),
				"valid_from":  fixturechange.Lit("2026-04-01"),
			},
			New: fixturechange.Values{
				"amount":      fixturechange.Lit("38"),
				"currency_id": fixturechange.RefTo("Currency", "USD"),
				"plan_id":     fixturechange.RefTo("Plan", "team"),
				"valid_from":  fixturechange.Lit("2026-04-01"),
			},
		},
		{Model: "PlanPrice", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"currency_id": fixturechange.RefTo("Currency", "EUR"),
				"plan_id":     fixturechange.RefTo("Plan", "scale"),
				"valid_from":  fixturechange.Lit("2026-03-01"),
			},
			New: fixturechange.Values{
				"amount":      fixturechange.Lit("199"),
				"currency_id": fixturechange.RefTo("Currency", "EUR"),
				"plan_id":     fixturechange.RefTo("Plan", "scale"),
				"valid_from":  fixturechange.Lit("2026-03-01"),
			},
		},
		{Model: "PlanPrice", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"currency_id": fixturechange.RefTo("Currency", "USD"),
				"plan_id":     fixturechange.RefTo("Plan", "scale"),
				"valid_from":  fixturechange.Lit("2026-03-01"),
			},
			New: fixturechange.Values{
				"amount":      fixturechange.Lit("219"),
				"currency_id": fixturechange.RefTo("Currency", "USD"),
				"plan_id":     fixturechange.RefTo("Plan", "scale"),
				"valid_from":  fixturechange.Lit("2026-03-01"),
			},
		},
		{Model: "Feature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("audit_log")},
			New: fixturechange.Values{
				"code": fixturechange.Lit("audit_log"),
				"id":   fixturechange.Lit("6"),
				"name": fixturechange.Lit("Audit log"),
				"unit": fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "audit_log"),
				"plan_id":    fixturechange.RefTo("Plan", "business"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "audit_log"),
				"plan_id":    fixturechange.RefTo("Plan", "business"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "projects"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "projects"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "storage"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "storage"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
				"quota":      fixturechange.Lit("5000"),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "api"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "api"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "sso"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "sso"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "priority_support"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "priority_support"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "PlanFeature", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "audit_log"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
			},
			New: fixturechange.Values{
				"feature_id": fixturechange.RefTo("Feature", "audit_log"),
				"plan_id":    fixturechange.RefTo("Plan", "scale"),
				"quota":      fixturechange.Null(),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"key": fixturechange.Lit("plan.scale.name"), "locale": fixturechange.Lit("en")},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("plan.scale.name"),
				"locale":  fixturechange.Lit("en"),
				"value":   fixturechange.Lit("Scale"),
			},
		},
		{Model: "Translation", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"key": fixturechange.Lit("plan.scale.name"), "locale": fixturechange.Lit("de")},
			New: fixturechange.Values{
				"context": fixturechange.Null(),
				"key":     fixturechange.Lit("plan.scale.name"),
				"locale":  fixturechange.Lit("de"),
				"value":   fixturechange.Lit("Scale"),
			},
		},
	},
}
