package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/checkout.yml, fixtures/storefront.yml, fixtures/access.yml against the state after baseline.
// 7 inserts, 2 updates, 0 deletes.
//
// Currency: 1 insert
// Country: 1 insert
// TaxRate: 3 inserts, 1 update
// PaymentProvider: 1 update
// ShippingZone: 1 insert
// ShippingMethod: 1 insert
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20270201100000GermanVatAndPoland),
		fixtureapply.Down(fixtureChanges20270201100000GermanVatAndPoland),
	)
}

var fixtureChanges20270201100000GermanVatAndPoland = fixturechange.Set{
	Name:            "20270201100000_fixture_german_vat_and_poland",
	SeedGuardTable:  "billing.currencies",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Country":         {Name: "countries", ID: "id", Key: "iso2", Serial: true},
		"Currency":        {Name: "billing.currencies", ID: "code", Key: "code"},
		"PaymentProvider": {Name: "billing.payment_providers", ID: "id"},
		"ShippingMethod":  {Name: "shipping_methods", ID: "id", Serial: true},
		"ShippingZone":    {Name: "shipping_zones", ID: "id", Key: "code", Serial: true},
		"TaxRate":         {Name: "billing.tax_rates", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "TaxRate", Kind: fixturechange.Update,
			Key: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "DE"),
				"tax_class":  fixturechange.Lit("standard"),
				"valid_from": fixturechange.Lit("2007-01-01"),
			},
			Old: fixturechange.Values{"valid_to": fixturechange.Null()},
			New: fixturechange.Values{"valid_to": fixturechange.Lit("2027-07-01")},
		},
		{Model: "PaymentProvider", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("stripe")},
			Old: fixturechange.Values{"supported_currencies": fixturechange.Lit(`["EUR","USD","GBP","CHF","SEK"]`)},
			New: fixturechange.Values{
				"supported_currencies": fixturechange.Lit(`["EUR","USD","GBP","CHF","SEK","PLN"]`),
			},
		},
		{Model: "Currency", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("PLN")},
			New: fixturechange.Values{
				"code":        fixturechange.Lit("PLN"),
				"minor_units": fixturechange.Lit("2"),
				"name":        fixturechange.Lit("Polish złoty"),
				"symbol":      fixturechange.Lit("zł"),
			},
		},
		{Model: "Country", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"iso2": fixturechange.Lit("PL")},
			New: fixturechange.Values{
				"currency_code": fixturechange.RefTo("Currency", "PLN"),
				"eu_member":     fixturechange.Lit("true"),
				"id":            fixturechange.Lit("9"),
				"iso2":          fixturechange.Lit("PL"),
				"iso3":          fixturechange.Lit("POL"),
				"name":          fixturechange.Lit(`{"de":"Polen","en":"Poland","pl":"Polska"}`),
			},
		},
		{Model: "TaxRate", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "DE"),
				"tax_class":  fixturechange.Lit("standard"),
				"valid_from": fixturechange.Lit("2027-07-01"),
			},
			New: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "DE"),
				"id":         fixturechange.Lit("18"),
				"rate":       fixturechange.Lit("0.2"),
				"tax_class":  fixturechange.Lit("standard"),
				"valid_from": fixturechange.Lit("2027-07-01"),
				"valid_to":   fixturechange.Null(),
			},
		},
		{Model: "TaxRate", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "PL"),
				"tax_class":  fixturechange.Lit("standard"),
				"valid_from": fixturechange.Lit("2011-01-01"),
			},
			New: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "PL"),
				"id":         fixturechange.Lit("19"),
				"rate":       fixturechange.Lit("0.23"),
				"tax_class":  fixturechange.Lit("standard"),
				"valid_from": fixturechange.Lit("2011-01-01"),
				"valid_to":   fixturechange.Null(),
			},
		},
		{Model: "TaxRate", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "PL"),
				"tax_class":  fixturechange.Lit("reduced"),
				"valid_from": fixturechange.Lit("2011-01-01"),
			},
			New: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "PL"),
				"id":         fixturechange.Lit("20"),
				"rate":       fixturechange.Lit("0.08"),
				"tax_class":  fixturechange.Lit("reduced"),
				"valid_from": fixturechange.Lit("2011-01-01"),
				"valid_to":   fixturechange.Null(),
			},
		},
		{Model: "ShippingZone", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("pl")},
			New: fixturechange.Values{
				"code":               fixturechange.Lit("pl"),
				"countries":          fixturechange.Lit(`["PL"]`),
				"free_shipping_over": fixturechange.Lit("199"),
				"id":                 fixturechange.Lit("6"),
				"name":               fixturechange.Lit("Poland"),
			},
		},
		{Model: "ShippingMethod", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("inpost-pl")},
			New: fixturechange.Values{
				"base_price":    fixturechange.Lit("12.99"),
				"carrier":       fixturechange.Lit("InPost"),
				"code":          fixturechange.Lit("inpost-pl"),
				"currency_code": fixturechange.RefTo("Currency", "PLN"),
				"id":            fixturechange.Lit("7"),
				"is_default":    fixturechange.Lit("true"),
				"max_days":      fixturechange.Lit("2"),
				"min_days":      fixturechange.Lit("1"),
				"name":          fixturechange.Lit(`{"en":"Parcel locker","pl":"Paczkomat"}`),
				"zone_id":       fixturechange.RefTo("ShippingZone", "pl"),
			},
		},
	},
}
