package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/checkout.yml, fixtures/storefront.yml, fixtures/access.yml against the state after 20270201100000_fixture_german_vat_and_poland.
// 4 inserts, 14 updates, 0 deletes.
//
// Category: 2 inserts, 12 updates
// CategorySEO: 2 inserts, 2 updates
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20270301100000CategoryTree),
		fixtureapply.Down(fixtureChanges20270301100000CategoryTree),
	)
}

var fixtureChanges20270301100000CategoryTree = fixturechange.Set{
	Name:            "20270301100000_fixture_category_tree",
	SeedGuardTable:  "billing.currencies",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"Category":    {Name: "catalog.categories", ID: "id", Key: "slug", Serial: true},
		"CategorySEO": {Name: "catalog.category_seo", ID: ""},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("apparel")},
			Old: fixturechange.Values{"name": fixturechange.Lit(`{"de":"Bekleidung","en":"Apparel"}`)},
			New: fixturechange.Values{
				"name": fixturechange.Lit(`{"de":"Bekleidung","en":"Apparel","fr":"Vêtements"}`),
			},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("womens")},
			Old: fixturechange.Values{"name": fixturechange.Lit(`{"de":"Damen","en":"Women"}`)},
			New: fixturechange.Values{"name": fixturechange.Lit(`{"de":"Damen","en":"Women","fr":"Femme"}`)},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("mens")},
			Old: fixturechange.Values{
				"name":     fixturechange.Lit(`{"de":"Herren","en":"Men"}`),
				"position": fixturechange.Lit("2"),
			},
			New: fixturechange.Values{
				"name":     fixturechange.Lit(`{"de":"Herren","en":"Men","fr":"Homme"}`),
				"position": fixturechange.Lit("3"),
			},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("kids")},
			Old: fixturechange.Values{
				"name":     fixturechange.Lit(`{"de":"Kinder","en":"Kids"}`),
				"position": fixturechange.Lit("3"),
			},
			New: fixturechange.Values{
				"name":     fixturechange.Lit(`{"de":"Kinder","en":"Kids","fr":"Enfant"}`),
				"position": fixturechange.Lit("4"),
			},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("home")},
			Old: fixturechange.Values{"name": fixturechange.Lit(`{"de":"Wohnen","en":"Home & living"}`)},
			New: fixturechange.Values{
				"name": fixturechange.Lit(`{"de":"Wohnen","en":"Home & living","fr":"Maison"}`),
			},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("kitchen")},
			Old: fixturechange.Values{"name": fixturechange.Lit(`{"de":"Küche","en":"Kitchen"}`)},
			New: fixturechange.Values{"name": fixturechange.Lit(`{"de":"Küche","en":"Kitchen","fr":"Cuisine"}`)},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("living")},
			Old: fixturechange.Values{"name": fixturechange.Lit(`{"de":"Wohnzimmer","en":"Living room"}`)},
			New: fixturechange.Values{
				"name": fixturechange.Lit(`{"de":"Wohnzimmer","en":"Living room","fr":"Salon"}`),
			},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("electronics")},
			Old: fixturechange.Values{"name": fixturechange.Lit(`{"de":"Elektronik","en":"Electronics"}`)},
			New: fixturechange.Values{
				"name": fixturechange.Lit(`{"de":"Elektronik","en":"Electronics","fr":"Électronique"}`),
			},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("cameras")},
			Old: fixturechange.Values{
				"name":     fixturechange.Lit(`{"de":"Kameras","en":"Cameras"}`),
				"position": fixturechange.Lit("3"),
			},
			New: fixturechange.Values{
				"name":     fixturechange.Lit(`{"de":"Kameras","en":"Cameras","fr":"Appareils photo"}`),
				"position": fixturechange.Lit("1"),
			},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("phones")},
			Old: fixturechange.Values{
				"name":     fixturechange.Lit(`{"de":"Handys","en":"Phones"}`),
				"position": fixturechange.Lit("1"),
			},
			New: fixturechange.Values{
				"name":     fixturechange.Lit(`{"de":"Handys","en":"Phones","fr":"Téléphones"}`),
				"position": fixturechange.Lit("2"),
			},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("TV-Audio")},
			Old: fixturechange.Values{
				"name":     fixturechange.Lit(`{"de":"TV & Audio","en":"TV & audio"}`),
				"position": fixturechange.Lit("2"),
				"tags":     fixturechange.Lit("[]"),
			},
			New: fixturechange.Values{
				"name":     fixturechange.Lit(`{"de":"TV & Audio","en":"TV & audio","fr":"TV & audio"}`),
				"position": fixturechange.Lit("3"),
				"tags":     fixturechange.Lit(`["home-cinema"]`),
			},
		},
		{Model: "CategorySEO", Kind: fixturechange.Update,
			Key: fixturechange.Values{"category_id": fixturechange.RefTo("Category", "apparel")},
			Old: fixturechange.Values{
				"meta_title": fixturechange.Lit(`{"de":"Bekleidung für alle","en":"Apparel for everyone"}`),
			},
			New: fixturechange.Values{
				"meta_title": fixturechange.Lit(`{"de":"Bekleidung für alle","en":"Apparel for everyone","fr":"Des vêtements pour tous"}`),
			},
		},
		{Model: "CategorySEO", Kind: fixturechange.Update,
			Key: fixturechange.Values{"category_id": fixturechange.RefTo("Category", "electronics")},
			Old: fixturechange.Values{"noindex": fixturechange.Lit("true")},
			New: fixturechange.Values{"noindex": fixturechange.Lit("false")},
		},
		{Model: "Category", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"slug": fixturechange.Lit("shoes")},
			New: fixturechange.Values{
				"id":        fixturechange.Lit("13"),
				"name":      fixturechange.Lit(`{"de":"Schuhe","en":"Shoes","fr":"Chaussures"}`),
				"parent_id": fixturechange.RefTo("Category", "apparel"),
				"position":  fixturechange.Lit("2"),
				"slug":      fixturechange.Lit("shoes"),
				"tags":      fixturechange.Lit(`["fashion","shoes"]`),
			},
		},
		{Model: "Category", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"slug": fixturechange.Lit("outdoor")},
			New: fixturechange.Values{
				"id":        fixturechange.Lit("14"),
				"name":      fixturechange.Lit(`{"de":"Draußen","en":"Outdoor","fr":"Plein air"}`),
				"parent_id": fixturechange.Null(),
				"position":  fixturechange.Lit("4"),
				"slug":      fixturechange.Lit("outdoor"),
				"tags":      fixturechange.Lit(`["seasonal"]`),
			},
		},
		{Model: "CategorySEO", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"category_id": fixturechange.RefTo("Category", "shoes")},
			New: fixturechange.Values{
				"category_id":      fixturechange.RefTo("Category", "shoes"),
				"meta_description": fixturechange.Lit(`{"en":"Sneakers, boots and sandals."}`),
				"meta_title":       fixturechange.Lit(`{"de":"Schuhe","en":"Shoes"}`),
				"noindex":          fixturechange.Lit("false"),
			},
		},
		{Model: "CategorySEO", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"category_id": fixturechange.RefTo("Category", "outdoor")},
			New: fixturechange.Values{
				"category_id":      fixturechange.RefTo("Category", "outdoor"),
				"meta_description": fixturechange.Null(),
				"meta_title":       fixturechange.Lit(`{"de":"Draußen leben","en":"Outdoor living"}`),
				"noindex":          fixturechange.Lit("true"),
			},
		},
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("garden")},
			Old: fixturechange.Values{
				"name":      fixturechange.Lit(`{"de":"Garten","en":"Garden"}`),
				"parent_id": fixturechange.RefTo("Category", "home"),
				"position":  fixturechange.Lit("3"),
				"tags":      fixturechange.Lit(`["home","seasonal"]`),
			},
			New: fixturechange.Values{
				"name":      fixturechange.Lit(`{"de":"Garten","en":"Garden","fr":"Jardin"}`),
				"parent_id": fixturechange.RefTo("Category", "outdoor"),
				"position":  fixturechange.Lit("1"),
				"tags":      fixturechange.Lit(`["outdoor","seasonal"]`),
			},
		},
	},
}
