package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/checkout.yml, fixtures/storefront.yml, fixtures/access.yml against the state after 20270405100000_fixture_park_sale_and_express.
// 0 inserts, 6 updates, 0 deletes.
//
// ShippingMethod: 1 update
// MenuItem: 5 updates
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20270405100100HeaderOrder),
		fixtureapply.Down(fixtureChanges20270405100100HeaderOrder),
	)
}

var fixtureChanges20270405100100HeaderOrder = fixturechange.Set{
	Name:            "20270405100100_fixture_header_order",
	SeedGuardTable:  "billing.currencies",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"MenuItem":       {Name: "menu_items", ID: "id", Serial: true},
		"ShippingMethod": {Name: "shipping_methods", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "ShippingMethod", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("dhl-standard")},
			Old: fixturechange.Values{"is_default": fixturechange.Lit("false")},
			New: fixturechange.Values{"is_default": fixturechange.Lit("true")},
		},
		{Model: "MenuItem", Kind: fixturechange.Update,
			Key: fixturechange.Values{"menu": fixturechange.Lit("header"), "slug": fixturechange.Lit("home")},
			Old: fixturechange.Values{"position": fixturechange.Lit("4")},
			New: fixturechange.Values{"position": fixturechange.Lit("5")},
		},
		{Model: "MenuItem", Kind: fixturechange.Update,
			Key: fixturechange.Values{"menu": fixturechange.Lit("header"), "slug": fixturechange.Lit("men")},
			Old: fixturechange.Values{"position": fixturechange.Lit("3")},
			New: fixturechange.Values{"position": fixturechange.Lit("4")},
		},
		{Model: "MenuItem", Kind: fixturechange.Update,
			Key: fixturechange.Values{"menu": fixturechange.Lit("header"), "slug": fixturechange.Lit("women")},
			Old: fixturechange.Values{"position": fixturechange.Lit("2")},
			New: fixturechange.Values{"position": fixturechange.Lit("3")},
		},
		{Model: "MenuItem", Kind: fixturechange.Update,
			Key: fixturechange.Values{"menu": fixturechange.Lit("header"), "slug": fixturechange.Lit("new")},
			Old: fixturechange.Values{"position": fixturechange.Lit("1")},
			New: fixturechange.Values{"position": fixturechange.Lit("2")},
		},
		{Model: "MenuItem", Kind: fixturechange.Update,
			Key: fixturechange.Values{"menu": fixturechange.Lit("header"), "slug": fixturechange.Lit("sale")},
			Old: fixturechange.Values{"position": fixturechange.Lit("99")},
			New: fixturechange.Values{"position": fixturechange.Lit("1")},
		},
	},
}
