package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/checkout.yml, fixtures/storefront.yml, fixtures/access.yml against the state after 20270607100000_fixture_audit_and_senders.
// 1 insert, 2 updates, 0 deletes.
//
// Category: 1 update
// ShippingMethod: 1 update
// MenuItem: 1 insert
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20270705100000AutumnCampaign),
		fixtureapply.Down(fixtureChanges20270705100000AutumnCampaign),
	)
}

var fixtureChanges20270705100000AutumnCampaign = fixturechange.Set{
	Name:            "20270705100000_fixture_autumn_campaign",
	SeedGuardTable:  "billing.currencies",
	MigrationsTable: "bun_migrations",
	AuditTable:      "fixture_audit",
	Tables: fixturechange.Tables{
		"Category":       {Name: "catalog.categories", ID: "id", Serial: true},
		"MenuItem":       {Name: "menu_items", ID: "id", Serial: true},
		"ShippingMethod": {Name: "shipping_methods", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("outdoor")},
			Old: fixturechange.Values{"tags": fixturechange.Lit(`["seasonal"]`)},
			New: fixturechange.Values{"tags": fixturechange.Lit(`["seasonal","autumn"]`)},
		},
		{Model: "ShippingMethod", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("dpd-eu")},
			Old: fixturechange.Values{"max_days": fixturechange.Lit("5"), "min_days": fixturechange.Lit("2")},
			New: fixturechange.Values{"max_days": fixturechange.Lit("6"), "min_days": fixturechange.Lit("3")},
		},
		{Model: "MenuItem", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"menu": fixturechange.Lit("header"), "slug": fixturechange.Lit("autumn")},
			New: fixturechange.Values{
				"id":       fixturechange.Lit("10"),
				"label":    fixturechange.Lit(`{"de":"Herbst-Edit","en":"Autumn edit"}`),
				"menu":     fixturechange.Lit("header"),
				"position": fixturechange.Lit("6"),
				"slug":     fixturechange.Lit("autumn"),
				"url":      fixturechange.Lit("/campaign/autumn"),
			},
		},
	},
}
