package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/checkout.yml, fixtures/storefront.yml, fixtures/access.yml against the database.
// 0 inserts, 1 update, 0 deletes.
//
// MenuItem: 1 update
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20270906100200ReturnsLinkAsInTheFile),
		fixtureapply.Down(fixtureChanges20270906100200ReturnsLinkAsInTheFile),
	)
}

var fixtureChanges20270906100200ReturnsLinkAsInTheFile = fixturechange.Set{
	Name:            "20270906100200_fixture_returns_link_as_in_the_file",
	SeedGuardTable:  "billing.currencies",
	MigrationsTable: "bun_migrations",
	AuditTable:      "fixture_audit",
	Tables: fixturechange.Tables{
		"MenuItem": {Name: "menu_items", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "MenuItem", Kind: fixturechange.Update,
			Key: fixturechange.Values{"menu": fixturechange.Lit("footer"), "slug": fixturechange.Lit("returns")},
			Old: fixturechange.Values{"url": fixturechange.Lit("/returns")},
			New: fixturechange.Values{"url": fixturechange.Lit("/help/returns")},
		},
	},
}
