package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/checkout.yml, fixtures/storefront.yml, fixtures/access.yml against the state after 20270405100100_fixture_header_order.
// 7 inserts, 5 updates, 0 deletes.
//
// PaymentProvider: 1 insert, 2 updates
// AdminPermission: 1 insert, 1 update
// AdminRole: 1 insert, 2 updates
// AdminRolePermission: 4 inserts
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20270503100000KlarnaAndFinanceRole),
		fixtureapply.Down(fixtureChanges20270503100000KlarnaAndFinanceRole),
	)
}

var fixtureChanges20270503100000KlarnaAndFinanceRole = fixturechange.Set{
	Name:            "20270503100000_fixture_klarna_and_finance_role",
	SeedGuardTable:  "billing.currencies",
	MigrationsTable: "bun_migrations",
	Tables: fixturechange.Tables{
		"AdminPermission":     {Name: "admin_permissions", ID: "id", Key: "code", Serial: true},
		"AdminRole":           {Name: "admin_roles", ID: "id", Key: "code"},
		"AdminRolePermission": {Name: "admin_role_permissions", ID: "id", Where: "role_id IN (SELECT id FROM admin_roles WHERE builtin)"},
		"PaymentProvider":     {Name: "billing.payment_providers", ID: "id"},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "AdminPermission", Kind: fixturechange.Update,
			ID:  "3",
			Key: fixturechange.Values{"code": fixturechange.Lit("catalog.publish")},
			Old: fixturechange.Values{"code": fixturechange.Lit("catalog.publish")},
			New: fixturechange.Values{"code": fixturechange.Lit("catalog.products.publish")},
		},
		{Model: "AdminRole", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("support")},
			Old: fixturechange.Values{"code": fixturechange.Lit("support")},
			New: fixturechange.Values{"code": fixturechange.Lit("customer-care")},
		},
		{Model: "PaymentProvider", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("stripe")},
			Old: fixturechange.Values{"display_name": fixturechange.Lit(`{"de":"Kreditkarte","en":"Credit card"}`)},
			New: fixturechange.Values{
				"display_name": fixturechange.Lit(`{"de":"Kreditkarte","en":"Credit card","fr":"Carte bancaire"}`),
			},
		},
		{Model: "PaymentProvider", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("paypal")},
			Old: fixturechange.Values{"supported_currencies": fixturechange.Lit(`["EUR","USD","GBP"]`)},
			New: fixturechange.Values{"supported_currencies": fixturechange.Lit(`["EUR","USD","GBP","CHF"]`)},
		},
		{Model: "AdminRole", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("customer-care")},
			Old: fixturechange.Values{"name": fixturechange.Lit("Customer support")},
			New: fixturechange.Values{"name": fixturechange.Lit("Customer care")},
		},
		{Model: "PaymentProvider", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("klarna")},
			New: fixturechange.Values{
				"active":               fixturechange.Lit("true"),
				"code":                 fixturechange.Lit("klarna"),
				"display_name":         fixturechange.Lit(`{"de":"Später bezahlen mit Klarna","en":"Pay later with Klarna"}`),
				"fee_percent":          fixturechange.Lit("2.99"),
				"kind":                 fixturechange.Lit("bnpl"),
				"supported_currencies": fixturechange.Lit(`["EUR","SEK","GBP"]`),
			},
		},
		{Model: "AdminPermission", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("payouts.read")},
			New: fixturechange.Values{
				"code":        fixturechange.Lit("payouts.read"),
				"description": fixturechange.Lit("See the payment providers' payouts"),
				"id":          fixturechange.Lit("8"),
			},
		},
		{Model: "AdminRole", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("finance")},
			New: fixturechange.Values{
				"builtin": fixturechange.Lit("true"),
				"code":    fixturechange.Lit("finance"),
				"name":    fixturechange.Lit("Finance"),
			},
		},
		{Model: "AdminRolePermission", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"permission_id": fixturechange.RefTo("AdminPermission", "payouts.read"),
				"role_id":       fixturechange.RefTo("AdminRole", "owner"),
			},
			New: fixturechange.Values{
				"permission_id": fixturechange.RefTo("AdminPermission", "payouts.read"),
				"role_id":       fixturechange.RefTo("AdminRole", "owner"),
			},
		},
		{Model: "AdminRolePermission", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"permission_id": fixturechange.RefTo("AdminPermission", "orders.read"),
				"role_id":       fixturechange.RefTo("AdminRole", "finance"),
			},
			New: fixturechange.Values{
				"permission_id": fixturechange.RefTo("AdminPermission", "orders.read"),
				"role_id":       fixturechange.RefTo("AdminRole", "finance"),
			},
		},
		{Model: "AdminRolePermission", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"permission_id": fixturechange.RefTo("AdminPermission", "orders.refund"),
				"role_id":       fixturechange.RefTo("AdminRole", "finance"),
			},
			New: fixturechange.Values{
				"permission_id": fixturechange.RefTo("AdminPermission", "orders.refund"),
				"role_id":       fixturechange.RefTo("AdminRole", "finance"),
			},
		},
		{Model: "AdminRolePermission", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"permission_id": fixturechange.RefTo("AdminPermission", "payouts.read"),
				"role_id":       fixturechange.RefTo("AdminRole", "finance"),
			},
			New: fixturechange.Values{
				"permission_id": fixturechange.RefTo("AdminPermission", "payouts.read"),
				"role_id":       fixturechange.RefTo("AdminRole", "finance"),
			},
		},
	},
}
