package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/checkout.yml, fixtures/storefront.yml, fixtures/access.yml, fixtures/customs.yml against the state after 20271101100000_fixture_denmark.
// 4 inserts, 0 updates, 0 deletes.
//
// Category: 1 insert
// CategorySEO: 1 insert
// AdminPermission: 1 insert
// AdminRolePermission: 1 insert
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20271103100000SmartHome),
		fixtureapply.Down(fixtureChanges20271103100000SmartHome),
	)
}

var fixtureChanges20271103100000SmartHome = fixturechange.Set{
	Name:            "20271103100000_fixture_smart_home",
	SeedGuardTable:  "billing.currencies",
	MigrationsTable: "bun_migrations",
	AuditTable:      "fixture_audit",
	Tables: fixturechange.Tables{
		"AdminPermission":     {Name: "admin_permissions", ID: "id", Key: "code", Serial: true},
		"AdminRole":           {Name: "admin_roles", ID: "id", Key: "code"},
		"AdminRolePermission": {Name: "admin_role_permissions", ID: "id", Where: "role_id IN (SELECT id FROM admin_roles WHERE builtin)"},
		"Category":            {Name: "catalog.categories", ID: "id", Key: "slug", Serial: true},
		"CategorySEO":         {Name: "catalog.category_seo", ID: ""},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Category", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"slug": fixturechange.Lit("smart-home")},
			New: fixturechange.Values{
				"id":        fixturechange.Lit("15"),
				"name":      fixturechange.Lit(`{"de":"Smart Home","en":"Smart home","fr":"Maison connectée"}`),
				"parent_id": fixturechange.RefTo("Category", "electronics"),
				"position":  fixturechange.Lit("4"),
				"slug":      fixturechange.Lit("smart-home"),
				"tags":      fixturechange.Lit(`["home","connected"]`),
			},
		},
		{Model: "CategorySEO", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"category_id": fixturechange.RefTo("Category", "smart-home")},
			New: fixturechange.Values{
				"category_id":      fixturechange.RefTo("Category", "smart-home"),
				"meta_description": fixturechange.Lit(`{"en":"Lights, plugs and thermostats."}`),
				"meta_title":       fixturechange.Lit(`{"de":"Smart Home","en":"Smart home"}`),
				"noindex":          fixturechange.Lit("false"),
			},
		},
		{Model: "AdminPermission", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("catalog.import")},
			New: fixturechange.Values{
				"code":        fixturechange.Lit("catalog.import"),
				"description": fixturechange.Lit("Import products from a spreadsheet"),
				"id":          fixturechange.Lit("9"),
			},
		},
		{Model: "AdminRolePermission", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"permission_id": fixturechange.RefTo("AdminPermission", "catalog.import"),
				"role_id":       fixturechange.RefTo("AdminRole", "merchandiser"),
			},
			New: fixturechange.Values{
				"permission_id": fixturechange.RefTo("AdminPermission", "catalog.import"),
				"role_id":       fixturechange.RefTo("AdminRole", "merchandiser"),
			},
		},
	},
}
