package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/checkout.yml, fixtures/storefront.yml, fixtures/access.yml, fixtures/customs.yml against the state after 20271004100000_fixture_hs_codes.
// 5 inserts, 1 update, 0 deletes.
//
// Currency: 1 insert
// Country: 1 insert
// TaxRate: 1 insert
// PaymentProvider: 1 update
// ShippingZone: 1 insert
// ShippingMethod: 1 insert
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20271101100000Denmark),
		fixtureapply.Down(fixtureChanges20271101100000Denmark),
	)
}

var fixtureChanges20271101100000Denmark = fixturechange.Set{
	Name:            "20271101100000_fixture_denmark",
	SeedGuardTable:  "billing.currencies",
	MigrationsTable: "bun_migrations",
	AuditTable:      "fixture_audit",
	Tables: fixturechange.Tables{
		"Country":         {Name: "countries", ID: "id", Key: "iso2", Serial: true},
		"Currency":        {Name: "billing.currencies", ID: "code", Key: "code"},
		"PaymentProvider": {Name: "billing.payment_providers", ID: "id"},
		"ShippingMethod":  {Name: "shipping_methods", ID: "id", Serial: true},
		"ShippingZone":    {Name: "shipping_zones", ID: "id", Key: "code", Serial: true},
		"TaxRate":         {Name: "billing.tax_rates", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "PaymentProvider", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("stripe")},
			Old: fixturechange.Values{
				"supported_currencies": fixturechange.Lit(`["EUR","USD","GBP","CHF","SEK","PLN"]`),
			},
			New: fixturechange.Values{
				"supported_currencies": fixturechange.Lit(`["EUR","USD","GBP","CHF","SEK","PLN","DKK"]`),
			},
		},
		{Model: "Currency", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("DKK")},
			New: fixturechange.Values{
				"code":        fixturechange.Lit("DKK"),
				"minor_units": fixturechange.Lit("2"),
				"name":        fixturechange.Lit("Danish krone"),
				"symbol":      fixturechange.Lit("kr."),
			},
		},
		{Model: "Country", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"iso2": fixturechange.Lit("DK")},
			New: fixturechange.Values{
				"currency_code": fixturechange.RefTo("Currency", "DKK"),
				"eu_member":     fixturechange.Lit("true"),
				"id":            fixturechange.Lit("10"),
				"iso2":          fixturechange.Lit("DK"),
				"iso3":          fixturechange.Lit("DNK"),
				"name":          fixturechange.Lit(`{"da":"Danmark","de":"Dänemark","en":"Denmark"}`),
			},
		},
		{Model: "TaxRate", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "DK"),
				"tax_class":  fixturechange.Lit("standard"),
				"valid_from": fixturechange.Lit("1992-01-01"),
			},
			New: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "DK"),
				"id":         fixturechange.Lit("22"),
				"rate":       fixturechange.Lit("0.25"),
				"tax_class":  fixturechange.Lit("standard"),
				"valid_from": fixturechange.Lit("1992-01-01"),
				"valid_to":   fixturechange.Null(),
			},
		},
		{Model: "ShippingZone", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("nordics")},
			New: fixturechange.Values{
				"code":               fixturechange.Lit("nordics"),
				"countries":          fixturechange.Lit(`["DK"]`),
				"free_shipping_over": fixturechange.Lit("750"),
				"id":                 fixturechange.Lit("7"),
				"name":               fixturechange.Lit("Nordics"),
			},
		},
		{Model: "ShippingMethod", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("postnord-dk")},
			New: fixturechange.Values{
				"base_price":    fixturechange.Lit("49"),
				"carrier":       fixturechange.Lit("PostNord"),
				"code":          fixturechange.Lit("postnord-dk"),
				"currency_code": fixturechange.RefTo("Currency", "DKK"),
				"id":            fixturechange.Lit("8"),
				"is_default":    fixturechange.Lit("true"),
				"max_days":      fixturechange.Lit("4"),
				"min_days":      fixturechange.Lit("2"),
				"name":          fixturechange.Lit(`{"da":"MyPack Home","en":"MyPack Home"}`),
				"zone_id":       fixturechange.RefTo("ShippingZone", "nordics"),
			},
		},
	},
}
