package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/checkout.yml, fixtures/storefront.yml, fixtures/access.yml against the state after 20270720100000_fixture_austrian_reduced_vat.
// 0 inserts, 2 updates, 0 deletes.
//
// Category: 1 update
// SenderIdentity: 1 update
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20270906100000AdminEdits),
		fixtureapply.Down(fixtureChanges20270906100000AdminEdits),
	)
}

var fixtureChanges20270906100000AdminEdits = fixturechange.Set{
	Name:            "20270906100000_fixture_admin_edits",
	SeedGuardTable:  "billing.currencies",
	MigrationsTable: "bun_migrations",
	AuditTable:      "fixture_audit",
	Tables: fixturechange.Tables{
		"Category":       {Name: "catalog.categories", ID: "id", Serial: true},
		"SenderIdentity": {Name: "sender_identities", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "Category", Kind: fixturechange.Update,
			Key: fixturechange.Values{"slug": fixturechange.Lit("kids")},
			Old: fixturechange.Values{"name": fixturechange.Lit(`{"de":"Kinder","en":"Kids","fr":"Enfant"}`)},
			New: fixturechange.Values{
				"name": fixturechange.Lit(`{"de":"Kinder & Jugendliche","en":"Kids & teens","fr":"Enfant"}`),
			},
		},
		{Model: "SenderIdentity", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("newsletter")},
			Old: fixturechange.Values{"display_name": fixturechange.Lit("Shop newsletter")},
			New: fixturechange.Values{"display_name": fixturechange.Lit("Shop news")},
		},
	},
}
