package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/checkout.yml, fixtures/storefront.yml, fixtures/access.yml against the state after 20270705100000_fixture_autumn_campaign.
// 1 insert, 1 update, 0 deletes.
//
// TaxRate: 1 insert, 1 update
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20270720100000AustrianReducedVat),
		fixtureapply.Down(fixtureChanges20270720100000AustrianReducedVat),
	)
}

var fixtureChanges20270720100000AustrianReducedVat = fixturechange.Set{
	Name:            "20270720100000_fixture_austrian_reduced_vat",
	SeedGuardTable:  "billing.currencies",
	MigrationsTable: "bun_migrations",
	AuditTable:      "fixture_audit",
	Tables: fixturechange.Tables{
		"Country": {Name: "countries", ID: "id", Key: "iso2", Serial: true},
		"TaxRate": {Name: "billing.tax_rates", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "TaxRate", Kind: fixturechange.Update,
			Key: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "AT"),
				"tax_class":  fixturechange.Lit("reduced"),
				"valid_from": fixturechange.Lit("1984-01-01"),
			},
			Old: fixturechange.Values{"valid_to": fixturechange.Null()},
			New: fixturechange.Values{"valid_to": fixturechange.Lit("2027-08-01")},
		},
		{Model: "TaxRate", Kind: fixturechange.Insert,
			Key: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "AT"),
				"tax_class":  fixturechange.Lit("reduced"),
				"valid_from": fixturechange.Lit("2027-08-01"),
			},
			New: fixturechange.Values{
				"country_id": fixturechange.RefTo("Country", "AT"),
				"id":         fixturechange.Lit("21"),
				"rate":       fixturechange.Lit("0.05"),
				"tax_class":  fixturechange.Lit("reduced"),
				"valid_from": fixturechange.Lit("2027-08-01"),
				"valid_to":   fixturechange.Null(),
			},
		},
	},
}
