package migrations

import (
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"
)

// Generated by bun-fixture-migrate: fixtures/reference.yml, fixtures/catalog.yml, fixtures/checkout.yml, fixtures/storefront.yml, fixtures/access.yml against the state after 20270503100000_fixture_klarna_and_finance_role.
// 2 inserts, 2 updates, 0 deletes.
//
// LoyaltyTier: 1 insert
// SenderIdentity: 1 insert, 2 updates
//
// Read it before you run it. Each change is guarded: a row is found by its
// natural key, an update or a delete only touches a row that still holds the
// old values, and an insert only runs when no row with that key exists.
// A guard that matches nothing is diagnosed rather than ignored, and unless
// Policy says otherwise it fails the migration. A failed migration is not
// left recorded as applied: if bun recorded it before running it, which it
// does unless the migrator is built WithMarkAppliedOnSuccess(true), Up
// removes that record from MigrationsTable so the migration runs again.
// Up and Down are called here, in this file, because bun names the
// migration after the file that registers it, and so does Up.
func init() {
	Migrations.MustRegister(
		fixtureapply.Up(fixtureChanges20270607100000AuditAndSenders),
		fixtureapply.Down(fixtureChanges20270607100000AuditAndSenders),
	)
}

var fixtureChanges20270607100000AuditAndSenders = fixturechange.Set{
	Name:            "20270607100000_fixture_audit_and_senders",
	SeedGuardTable:  "billing.currencies",
	MigrationsTable: "bun_migrations",
	AuditTable:      "fixture_audit",
	Tables: fixturechange.Tables{
		"LoyaltyTier":    {Name: "loyalty_tiers", ID: "id", Serial: true},
		"SenderIdentity": {Name: "sender_identities", ID: "id", Serial: true},
	},
	Policy: fixturechange.Policy{
		MissingRow: "error", ChangedRow: "warn", IDDrift: "error", DuplicateKey: "error",
	},
	Changes: []fixturechange.Change{
		{Model: "SenderIdentity", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("orders")},
			Old: fixturechange.Values{"reply_to": fixturechange.Lit("Support@Shop.example")},
			New: fixturechange.Values{"reply_to": fixturechange.Lit("support@shop.example")},
		},
		{Model: "SenderIdentity", Kind: fixturechange.Update,
			Key: fixturechange.Values{"code": fixturechange.Lit("support")},
			Old: fixturechange.Values{"email": fixturechange.Lit("Support@Shop.example")},
			New: fixturechange.Values{"email": fixturechange.Lit("support@shop.example")},
		},
		{Model: "LoyaltyTier", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("platinum")},
			New: fixturechange.Values{
				"code":             fixturechange.Lit("platinum"),
				"discount_percent": fixturechange.Lit("7.5"),
				"id":               fixturechange.Lit("4"),
				"min_points":       fixturechange.Lit("20000"),
				"name":             fixturechange.Lit(`{"de":"Platin","en":"Platinum"}`),
			},
		},
		{Model: "SenderIdentity", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"code": fixturechange.Lit("marketplace")},
			New: fixturechange.Values{
				"code":         fixturechange.Lit("marketplace"),
				"display_name": fixturechange.Lit("Shop marketplace"),
				"email":        fixturechange.Lit("marketplace@shop.example"),
				"id":           fixturechange.Lit("4"),
				"reply_to":     fixturechange.Lit("support@shop.example"),
			},
		},
	},
}
