package dbtest_test

// Edge cases, each against a real PostgreSQL and, where dbfixture is involved,
// the real loader. Each test names the way the case went wrong before.

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"

	fixturemigrate "github.com/RELAXccc/bun-fixture-migrate"
	"github.com/RELAXccc/bun-fixture-migrate/fixtureapply"
	"github.com/RELAXccc/bun-fixture-migrate/fixturechange"

	"github.com/uptrace/bun"
)

func run(t *testing.T, db bun.IDB, stmts ...string) {
	t.Helper()
	for _, stmt := range stmts {
		if _, err := db.ExecContext(context.Background(), stmt); err != nil {
			t.Fatalf("%s: %v", stmt, err)
		}
	}
}

// insertPlan is a change set that inserts one plan with an explicit id into a
// serial table.
func insertPlan(table, name, id string) fixturechange.Set {
	return fixturechange.Set{
		Name:   "20260921120000_fixture_sequence",
		Tables: fixturechange.Tables{"Plan": {Name: table, ID: "id", Key: "name", Serial: true}},
		Changes: []fixturechange.Change{{Model: "Plan", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"name": fixturechange.Lit(name)},
			New: fixturechange.Values{"id": fixturechange.Lit(id), "name": fixturechange.Lit(name)}}},
	}
}

// setval is not transactional, so a sequence moved back to the highest id
// hands out again the values other sessions already drew, and deleted ids.
// Before: an explicit id 10 into a table whose sequence stood at 100 set it to
// 10, and the next ordinary insert got 11.
func TestASequenceIsNeverMovedBack(t *testing.T) {
	db := connect(t)
	ctx := context.Background()
	run(t, db,
		"DROP TABLE IF EXISTS seq_plans",
		"CREATE TABLE seq_plans (id bigserial PRIMARY KEY, name text UNIQUE NOT NULL)",
		"INSERT INTO seq_plans (name) VALUES ('a'), ('b'), ('c')",
		"SELECT setval('seq_plans_id_seq', 100)")
	if err := fixtureapply.Apply(ctx, db, insertPlan("seq_plans", "x", "10"), quiet()); err != nil {
		t.Fatal(err)
	}
	if got := scan[int64](t, db, "SELECT last_value FROM seq_plans_id_seq"); got != 100 {
		t.Fatalf("the sequence was moved from 100 to %d", got)
	}
	// Behind the ids written, it is moved forward.
	if err := fixtureapply.Apply(ctx, db, insertPlan("seq_plans", "y", "500"), quiet()); err != nil {
		t.Fatal(err)
	}
	if got := scan[int64](t, db, "SELECT last_value FROM seq_plans_id_seq"); got != 500 {
		t.Fatalf("the sequence should stand at 500, got %d", got)
	}
}

// A sequence that was never called is compared with where it starts.
func TestAFreshSequenceStartingHighIsLeftAlone(t *testing.T) {
	db := connect(t)
	run(t, db,
		"DROP TABLE IF EXISTS seq_plans",
		"CREATE TABLE seq_plans (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY, name text UNIQUE)")
	if err := fixtureapply.Apply(context.Background(), db, insertPlan("seq_plans", "x", "3"), quiet()); err != nil {
		t.Fatal(err)
	}
	run(t, db, "INSERT INTO seq_plans (name) VALUES ('next')")
	if got := scan[int64](t, db, "SELECT id FROM seq_plans WHERE name = 'next'"); got != 1000 {
		t.Fatalf("the next id should still be the start, 1000, got %d", got)
	}
}

// Ids below 1000 are kept for master data: a schema migration restarted the
// sequence at 1000, and the application has not inserted a row yet. A
// sequence not called since has no last value to pg_sequence_last_value, and
// its start value is not where RESTART left it: an explicit id 3 moved the
// sequence back to 3, and SyncSequences to the highest id, into the ids kept
// for master data.
func TestARestartedSequenceIsNotMovedBack(t *testing.T) {
	db := connect(t)
	ctx := context.Background()
	reset := func(restart string) {
		run(t, db, "DROP TABLE IF EXISTS seq_plans",
			"CREATE TABLE seq_plans (id bigserial PRIMARY KEY, name text UNIQUE NOT NULL)",
			"ALTER SEQUENCE seq_plans_id_seq RESTART WITH "+restart,
			"INSERT INTO seq_plans (id, name) VALUES (1, 'free'), (2, 'team')")
	}
	next := func() int64 { return scan[int64](t, db, "SELECT nextval('seq_plans_id_seq')") }

	reset("1000")
	if err := fixtureapply.Apply(ctx, db, insertPlan("seq_plans", "pro", "3"), quiet()); err != nil {
		t.Fatal(err)
	}
	if got := next(); got != 1000 {
		t.Fatalf("after an explicit id 3 the next id is %d, not 1000", got)
	}
	reset("1000")
	if moved, err := fixtureapply.SyncSequences(ctx, db, "seq_plans"); err != nil || len(moved) != 0 {
		t.Fatalf("SyncSequences moved %v: %v", moved, err)
	}
	if got := next(); got != 1000 {
		t.Fatalf("after SyncSequences the next id is %d, not 1000", got)
	}

	// The id the sequence hands out next is taken: it moves past it.
	reset("1000")
	if err := fixtureapply.Apply(ctx, db, insertPlan("seq_plans", "pro", "1000"), quiet()); err != nil {
		t.Fatal(err)
	}
	if got := next(); got != 1001 {
		t.Fatalf("after an explicit id 1000 the next id is %d, not 1001", got)
	}
	reset("2")
	if moved, err := fixtureapply.SyncSequences(ctx, db, "seq_plans"); err != nil || len(moved) != 1 {
		t.Fatalf("the sequence would hand out 2 again: moved %v, %v", moved, err)
	}
	if got := next(); got != 3 {
		t.Fatalf("after SyncSequences the next id is %d, not 3", got)
	}
}

// A mixed-case table: pg_get_serial_sequence parses its argument as SQL, and
// unquoted it folded the name and found no sequence at all.
func TestTheSequenceOfAMixedCaseTableIsFound(t *testing.T) {
	db := connect(t)
	run(t, db,
		`DROP TABLE IF EXISTS "SeqPlans"`,
		`CREATE TABLE "SeqPlans" (id bigserial PRIMARY KEY, name text UNIQUE NOT NULL)`)
	if err := fixtureapply.Apply(context.Background(), db, insertPlan("SeqPlans", "x", "7"), quiet()); err != nil {
		t.Fatal(err)
	}
	run(t, db, `INSERT INTO "SeqPlans" (name) VALUES ('next')`)
	if got := scan[int64](t, db, `SELECT id FROM "SeqPlans" WHERE name = 'next'`); got != 8 {
		t.Fatalf("the sequence was left behind: next id %d", got)
	}
}

// dbfixture writes explicit ids and a sequence does not see them go by, so
// the application's first insert after seeding failed on the primary key.
// SyncSequences finds every serial and identity column, whatever its name or
// the table's case, and moves only what is behind.
func TestSyncSequencesAfterSeeding(t *testing.T) {
	db := connect(t)
	ctx := context.Background()
	run(t, db,
		`DROP TABLE IF EXISTS "SeedPlans", seed_items`,
		`CREATE TABLE "SeedPlans" ("PlanID" bigserial PRIMARY KEY, name text UNIQUE NOT NULL)`,
		`CREATE TABLE seed_items (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, `+
			`pos serial, label text)`,
		`INSERT INTO "SeedPlans" ("PlanID", name) VALUES (1, 'a'), (2, 'b')`,
		`INSERT INTO seed_items (id, pos, label) VALUES (40, 3, 'x')`,
		`SELECT setval('seed_items_pos_seq', 90)`)
	moved, err := fixtureapply.SyncSequences(ctx, db, "SeedPlans", "seed_items")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Join(moved, ",") != "SeedPlans.PlanID,seed_items.id" {
		t.Fatalf("moved %v; pos stood at 90, ahead of 3, and stays", moved)
	}
	run(t, db, `INSERT INTO "SeedPlans" (name) VALUES ('c')`, `INSERT INTO seed_items (label) VALUES ('y')`)
	if got := scan[int64](t, db, `SELECT "PlanID" FROM "SeedPlans" WHERE name = 'c'`); got != 3 {
		t.Fatalf("next plan id %d", got)
	}
	if got := scan[string](t, db, `SELECT id || '/' || pos FROM seed_items WHERE label = 'y'`); got != "41/91" {
		t.Fatalf("next item %s", got)
	}
	if moved, err := fixtureapply.SyncSequences(ctx, db, "SeedPlans", "seed_items"); err != nil || len(moved) != 0 {
		t.Fatalf("a second call has nothing to do: %v %v", moved, err)
	}
	if _, err := fixtureapply.SyncSequences(ctx, db, "no_such_table"); err == nil {
		t.Fatal("an unknown table is an error, not nothing to do")
	}
	if _, err := fixtureapply.SyncSequences(ctx, db, "x; DROP TABLE seed_items"); err == nil {
		t.Fatal("a table name is an identifier")
	}
}

// A dry run leaves the sequence where it was, since a rollback cannot move it
// back, and reports what the migration would do instead.
func TestADryRunLeavesTheSequenceAlone(t *testing.T) {
	db := connect(t)
	ctx := context.Background()
	run(t, db,
		"DROP TABLE IF EXISTS seq_plans",
		"CREATE TABLE seq_plans (id bigserial PRIMARY KEY, name text UNIQUE NOT NULL)",
		"INSERT INTO seq_plans (name) VALUES ('a')")
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	var outcomes []fixtureapply.Outcome
	err = fixtureapply.Apply(ctx, tx, insertPlan("seq_plans", "x", "50"), quiet(), fixtureapply.WithDryRun(),
		fixtureapply.WithReport(func(o fixtureapply.Outcome) { outcomes = append(outcomes, o) }))
	if err != nil {
		t.Fatal(err)
	}
	if err := tx.Rollback(); err != nil {
		t.Fatal(err)
	}
	if got := scan[int64](t, db, "SELECT last_value FROM seq_plans_id_seq"); got != 1 {
		t.Fatalf("a dry run moved the sequence to %d", got)
	}
	last := outcomes[len(outcomes)-1]
	if last.Status != fixtureapply.StatusSequence || !strings.Contains(last.Message, "a dry run leaves alone") {
		t.Fatalf("the sequence step has to be reported: %+v", outcomes)
	}
}

// bun puts WithTableName's name into SQL unquoted, so PostgreSQL folds it.
// Quoted, the tool looked for another table, found none, and a failed
// migration stayed recorded.
func TestAMixedCaseMigrationsTableIsTheOneBunUses(t *testing.T) {
	db := testDB(t)
	seed(t, db)
	ctx := context.Background()
	run(t, db,
		"DROP TABLE IF EXISTS fixture_migrations",
		"CREATE TABLE Fixture_Migrations (id bigserial PRIMARY KEY, name varchar, group_id bigint, "+
			"migrated_at timestamptz NOT NULL DEFAULT current_timestamp)",
		"INSERT INTO Fixture_Migrations (name, group_id) VALUES ('20260921120000', 1)")
	applied, exists, err := fixturemigrate.ReadApplied(ctx, db, "Fixture_Migrations")
	if err != nil || !exists || len(applied) != 1 {
		t.Fatalf("ReadApplied: %v %v %v", applied, exists, err)
	}
	failing := fixturechange.Set{
		Name: "x", MigrationsTable: "Fixture_Migrations", Tables: tables(),
		Changes: []fixturechange.Change{{Model: "Plan", Kind: fixturechange.Update,
			Key: fixturechange.Values{"name": fixturechange.Lit("gone")},
			Old: fixturechange.Values{"price_cents": fixturechange.Lit("1")},
			New: fixturechange.Values{"price_cents": fixturechange.Lit("2")}}},
	}
	err = fixtureapply.Apply(ctx, db, failing, quiet(), fixtureapply.WithMigrationName("20260921120000"))
	if err == nil || !strings.Contains(err.Error(), "that record was removed") {
		t.Fatalf("expected the record to be taken back: %v", err)
	}
	if got := scan[int64](t, db, "SELECT count(*) FROM fixture_migrations"); got != 0 {
		t.Fatal("the record is still there")
	}
}

// A generated column is the database's to fill. Before, export wrote it, and
// the tool's own lint then refused the file it had written.
func TestExportLeavesGeneratedColumnsOut(t *testing.T) {
	db := connect(t)
	ctx := context.Background()
	run(t, db,
		"DROP TABLE IF EXISTS gen_items",
		"CREATE TABLE gen_items (id bigint PRIMARY KEY, name text UNIQUE NOT NULL, price int NOT NULL, "+
			"doubled int GENERATED ALWAYS AS (price * 2) STORED)",
		"INSERT INTO gen_items VALUES (1, 'a', 10)")
	cfg := &fixturemigrate.Config{Models: map[string]*fixturemigrate.Model{"GenItem": {Table: "gen_items", Key: []string{"name"}}}}
	if err := cfg.Prepare(); err != nil {
		t.Fatal(err)
	}
	tables := schemaOf(t, db)
	snap, err := fixturemigrate.DatabaseSnapshot(ctx, db, cfg, tables, fixturemigrate.SnapshotOptions{})
	if err != nil {
		t.Fatal(err)
	}
	data, err := fixturemigrate.Export(cfg, snap, tables, nil)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), "doubled") {
		t.Fatalf("the generated column was exported:\n%s", data)
	}
	back := fixtureSnapshot(t, cfg, string(data), "export")
	fixturemigrate.LintColumns(cfg, back, tables)
	if len(back.Findings) != 0 {
		t.Fatalf("the tool refuses its own export: %+v", back.Findings)
	}
}

// GENERATED ALWAYS AS IDENTITY refuses an explicit id from anybody, so an
// export that writes the ids cannot be loaded.
func TestExportLeavesAnAlwaysIdentityOut(t *testing.T) {
	db := connect(t)
	ctx := context.Background()
	run(t, db,
		"DROP TABLE IF EXISTS ga_items",
		"CREATE TABLE ga_items (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name text UNIQUE NOT NULL)",
		"INSERT INTO ga_items (name) VALUES ('a'), ('b')")
	cfg := &fixturemigrate.Config{Models: map[string]*fixturemigrate.Model{"GaItem": {Table: "ga_items", Key: []string{"name"}}}}
	if err := cfg.Prepare(); err != nil {
		t.Fatal(err)
	}
	tables := schemaOf(t, db)
	snap, err := fixturemigrate.DatabaseSnapshot(ctx, db, cfg, tables, fixturemigrate.SnapshotOptions{})
	if err != nil {
		t.Fatal(err)
	}
	data, err := fixturemigrate.Export(cfg, snap, tables, nil)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), "\n      id:") {
		t.Fatalf("the identity was exported:\n%s", data)
	}
	withID := fixtureSnapshot(t, cfg, "- model: GaItem\n  rows:\n    - _id: a\n      id: 1\n      name: a\n", "fixture")
	fixturemigrate.LintColumns(cfg, withID, tables)
	if len(withID.Findings) != 1 || !strings.Contains(withID.Findings[0].Detail, "GENERATED ALWAYS") {
		t.Fatalf("an explicit id has to be reported: %+v", withID.Findings)
	}
}

// text/template reads "$.Region.1m.ID" as a malformed number. Before, a key
// starting with a digit became exactly such an anchor, and dbfixture refused
// the export.
func TestAnExportedAnchorIsOneATemplateCanName(t *testing.T) {
	db := itemDB(t)
	ctx := context.Background()
	run(t, db,
		"INSERT INTO regions (id, code, name) VALUES (1, '1M', 'one month')",
		"INSERT INTO items (id, region_id, name, cost, production_max, ratio, active) VALUES (1, 1, '2 hammers', 1, 1, 1, true)")
	cfg := itemConfig(t)
	tables := schemaOf(t, db)
	snap, err := fixturemigrate.DatabaseSnapshot(ctx, db, cfg, tables, fixturemigrate.SnapshotOptions{})
	if err != nil {
		t.Fatal(err)
	}
	data, err := fixturemigrate.Export(cfg, snap, tables, nil)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "{{ $.Region.r1m.ID }}") {
		t.Fatalf("expected the anchor r1m:\n%s", data)
	}
	fresh := itemDB(t)
	loadFixture(t, fresh, string(data))
	if got := itemRegion(t, fresh, "2 hammers"); got != "1M" {
		t.Fatalf("dbfixture bound the item to %s", got)
	}
}

// An anchor text/template cannot name is refused with a sentence about the
// anchor, and dbfixture refuses the file too.
func TestATemplateNamingAnUnnameableAnchorIsRefused(t *testing.T) {
	cfg := itemConfig(t)
	text := strings.Replace(itemFixture, "    - _id: us\n", "    - _id: north-america\n", 1)
	text = strings.Replace(text, "{{ $.Region.us.ID }}", "{{ $.Region.north-america.ID }}", 1)
	if err := tryLoad(itemDB(t), text); err == nil {
		t.Fatal("dbfixture loaded it; the tool's premise has changed")
	}
	doc, err := fixturemigrate.ParseDoc([]byte(text))
	if err != nil {
		t.Fatal(err)
	}
	_, err = fixturemigrate.FixtureSnapshot(cfg, doc, "fixture.yml")
	if err == nil || !strings.Contains(err.Error(), `"north-america" is not a name text/template can follow`) {
		t.Fatalf("expected the anchor to be named: %v", err)
	}
}

// Two replicas of an application migrate at the same start-up. Without a
// unique index nothing in the database stops both from finding the row
// missing and both inserting it; the advisory lock makes the second wait and
// then find it there.
func TestConcurrentChangeSetsDoNotBothInsert(t *testing.T) {
	db := connect(t)
	ctx := context.Background()
	run(t, db,
		"DROP TABLE IF EXISTS race_plans",
		"CREATE TABLE race_plans (id bigserial PRIMARY KEY, name text NOT NULL)")
	set := fixturechange.Set{Name: "race",
		Tables: fixturechange.Tables{"Plan": {Name: "race_plans", ID: "id", Key: "name"}},
		Changes: []fixturechange.Change{{Model: "Plan", Kind: fixturechange.Insert,
			Key: fixturechange.Values{"name": fixturechange.Lit("pro")},
			New: fixturechange.Values{"name": fixturechange.Lit("pro")}}}}

	first, err := db.BeginTx(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	if err := fixtureapply.Apply(ctx, first, set, quiet()); err != nil {
		t.Fatal(err)
	}
	done := make(chan error, 1)
	go func() { done <- fixtureapply.Apply(ctx, db, set, quiet()) }()
	select {
	case err := <-done:
		t.Fatalf("the second change set ran while the first was open: %v", err)
	case <-time.After(300 * time.Millisecond):
	}
	if err := first.Commit(); err != nil {
		t.Fatal(err)
	}
	if err := <-done; err != nil {
		t.Fatalf("the second change set: %v", err)
	}
	if got := scan[int64](t, db, "SELECT count(*) FROM race_plans"); got != 1 {
		t.Fatalf("%d rows named pro", got)
	}
}

func deletePlan(cascade bool) fixturechange.Set {
	return fixturechange.Set{Name: "delete",
		Tables: fixturechange.Tables{"Plan": {Name: "del_plans", ID: "id", Key: "name", Cascade: cascade}},
		Changes: []fixturechange.Change{{Model: "Plan", Kind: fixturechange.Delete,
			Key: fixturechange.Values{"name": fixturechange.Lit("old")},
			Old: fixturechange.Values{"id": fixturechange.Lit("1"), "name": fixturechange.Lit("old")}}}}
}

// Deleting a plan must not quietly delete, or detach, the subscriptions on
// it: they are not master data and the change set knows nothing of them.
func TestADeleteDoesNotCascadeIntoOtherRows(t *testing.T) {
	db := connect(t)
	ctx := context.Background()
	for _, action := range []string{"CASCADE", "SET NULL", "RESTRICT"} {
		t.Run(action, func(t *testing.T) {
			run(t, db,
				"DROP TABLE IF EXISTS del_subs, del_plans",
				"CREATE TABLE del_plans (id bigint PRIMARY KEY, name text UNIQUE NOT NULL)",
				"CREATE TABLE del_subs (id bigint PRIMARY KEY, plan_id bigint REFERENCES del_plans (id) ON DELETE "+action+")",
				"INSERT INTO del_plans VALUES (1, 'old'), (2, 'other')",
				"INSERT INTO del_subs VALUES (10, 1), (11, 1), (12, 2)")
			err := fixtureapply.Apply(ctx, db, deletePlan(false), quiet())
			if err == nil || !strings.Contains(err.Error(), "2 rows of del_subs point at del_plans name=old") {
				t.Fatalf("expected the delete to be refused with the rows named: %v", err)
			}
			if got := scan[int64](t, db, "SELECT count(*) FROM del_subs WHERE plan_id = 1"); got != 2 {
				t.Fatalf("the subscriptions were touched: %d left", got)
			}
			if action == "RESTRICT" {
				return
			}
			// Allowed for the model, the delete goes through and takes the
			// foreign key's action.
			if err := fixtureapply.Apply(ctx, db, deletePlan(true), quiet()); err != nil {
				t.Fatalf("with deletes: cascade: %v", err)
			}
			if got := scan[int64](t, db, "SELECT count(*) FROM del_plans WHERE name = 'old'"); got != 0 {
				t.Fatal("the plan was not deleted")
			}
		})
	}
	// Nothing pointing at it: the delete goes through without being allowed.
	run(t, db, "DELETE FROM del_subs WHERE plan_id = 1", "INSERT INTO del_plans VALUES (1, 'old') ON CONFLICT DO NOTHING")
	if err := fixtureapply.Apply(ctx, db, deletePlan(false), quiet()); err != nil {
		t.Fatalf("a row nothing points at: %v", err)
	}
}

// A category tree: a parent's children point at it from the same table.
func TestADeleteDoesNotCascadeThroughItsOwnTable(t *testing.T) {
	db := connect(t)
	run(t, db,
		"DROP TABLE IF EXISTS del_categories",
		"CREATE TABLE del_categories (id bigint PRIMARY KEY, name text UNIQUE NOT NULL, "+
			"parent_id bigint REFERENCES del_categories (id) ON DELETE CASCADE)",
		"INSERT INTO del_categories VALUES (1, 'root', NULL), (2, 'child', 1)")
	set := fixturechange.Set{Name: "tree",
		Tables: fixturechange.Tables{"Category": {Name: "del_categories", ID: "id", Key: "name"}},
		Changes: []fixturechange.Change{{Model: "Category", Kind: fixturechange.Delete,
			Key: fixturechange.Values{"name": fixturechange.Lit("root")},
			Old: fixturechange.Values{"id": fixturechange.Lit("1"), "name": fixturechange.Lit("root"),
				"parent_id": fixturechange.Null()}}}}
	err := fixtureapply.Apply(context.Background(), db, set, quiet())
	if err == nil || !strings.Contains(err.Error(), "1 row of del_categories point at") {
		t.Fatalf("expected the child to stop the delete: %v", err)
	}
}

// Sync from Go, the way a development server or a test's setup calls it.
func TestSyncFromGo(t *testing.T) {
	db := itemDB(t)
	cfg := itemConfig(t)
	ctx := context.Background()
	files := []fixturemigrate.FixtureFile{{Path: "fixture.yml", Data: []byte(itemFixture)}}

	res, err := fixturemigrate.Sync(ctx, db, cfg, files, fixturemigrate.SyncOptions{DryRun: true})
	if err != nil || res.Applied || len(res.Diff.Changes) != 4 {
		t.Fatalf("dry run: %v %+v", err, res)
	}
	if got := scan[int64](t, db, "SELECT count(*) FROM items"); got != 0 {
		t.Fatal("a dry run changed the database")
	}
	if res, err = fixturemigrate.Sync(ctx, db, cfg, files, fixturemigrate.SyncOptions{}); err != nil || !res.Applied {
		t.Fatalf("sync: %v %+v", err, res)
	}
	if res, err = fixturemigrate.Sync(ctx, db, cfg, files, fixturemigrate.SyncOptions{}); err != nil ||
		res.Applied || len(res.Diff.Changes) != 0 {
		t.Fatalf("a second sync has nothing to do: %v %+v", err, res)
	}
	renamed := []fixturemigrate.FixtureFile{{Data: []byte(strings.Replace(itemFixture, `name: "rope"`, `name: "cord"`, 1))}}
	if _, err := fixturemigrate.Sync(ctx, db, cfg, renamed, fixturemigrate.SyncOptions{}); !errors.Is(err, fixturemigrate.ErrSyncRefused) {
		t.Fatalf("a rename is refused: %v", err)
	}
}

// Sync applies its changes as a generated migration does, under the
// configuration's lock_timeout: it used to leave it out, and waited behind an
// admin's open transaction for as long as the admin did.
func TestSyncKeepsToTheLockTimeout(t *testing.T) {
	db := itemDB(t)
	cfg := itemConfig(t)
	ctx := context.Background()
	files := []fixturemigrate.FixtureFile{{Path: "fixture.yml", Data: []byte(itemFixture)}}
	if _, err := fixturemigrate.Sync(ctx, db, cfg, files, fixturemigrate.SyncOptions{}); err != nil {
		t.Fatal(err)
	}
	admin, err := db.BeginTx(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Rollback()
	if _, err := admin.ExecContext(ctx, "SELECT * FROM items WHERE name = 'anvil' FOR UPDATE"); err != nil {
		t.Fatal(err)
	}
	cfg.LockTimeout = "200ms"
	changed := []fixturemigrate.FixtureFile{{Path: "fixture.yml",
		Data: []byte(strings.Replace(itemFixture, "cost: 120", "cost: 130", 1))}}
	waitAtMost, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	_, err = fixturemigrate.Sync(waitAtMost, db, cfg, changed, fixturemigrate.SyncOptions{})
	var ce *fixtureapply.ChangeError
	if !errors.As(err, &ce) || ce.Outcome.Problem != fixtureapply.ProblemLockTimeout {
		t.Fatalf("want the lock timeout of 200ms, got %v", err)
	}
	if err := admin.Rollback(); err != nil {
		t.Fatal(err)
	}
	if res, err := fixturemigrate.Sync(ctx, db, cfg, changed, fixturemigrate.SyncOptions{}); err != nil || !res.Applied {
		t.Fatalf("once the admin is done: %v", err)
	}
}
